{
  "hash": "5109b7cc0243974e8c86c248a34a5047",
  "result": {
    "engine": "knitr",
    "markdown": "# World Bank (WB) {#sec-wb}\n\n\n\n\n\n\n\n\n\n\n\n:::::: {#obj-wb-objectives}\n::::: my-objectives\n::: my-objectives-header\nChapter section list\n:::\n\n::: my-objectives-container\n:::\n:::::\n::::::\n\n## Download World Bank Data {#sec-wb-download}\n\nThe World Bank Classification can be downloaded from [How does the World\nBank classify\ncountries?](https://datahelpdesk.worldbank.org/knowledgebase/articles/378834-how-does-the-world-bank-classify-countries).\nAt the bottom of the page you can see the line \"Download an Excel file\nof historical classifications by income.\", providing a link with word\n\"Download\". The downloaded file `CLASS.xlsx` does *not* contain a\nhistorical classification by income but the general classification\nsystem of the last available year (2023).\n\nYes, there is another Excel file `OGHIST.xslx` with the historical\ncutoffs for incomes and lending categories, dating from 1987 to 2023.\nBut the download link for this file is located at another web page:\n[World Bank Country and Lending\nGroups](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519).\nOn this page you will also find the updates for the cutoffs for\ncountries <a class='glossary' title='Gross National Income (GNI) is a measure of a country’s income, which includes all the income earned by a country’s residents, businesses, and earnings from foreign sources. It is defined as the total amount of money earned by a nation’s people and businesses, no matter where it was earned. GNI is an alternative to GDP as a way to measure and track a nation’s wealth, as it calculates income instead of output.'>GNI</a> income per capita which is important for\nthe lending eligibility of countries. [World Bank country\nclassifications by income level for\n2024-2025](https://blogs.worldbank.org/en/opendata/world-bank-country-classifications-by-income-level-for-2024-2025)\nhas the current updated values and changes over the last year.\n\nThe file `CLASS.xlsx` am interested here consists of three sheets:\n\n1.  \"List of Economoies\"\n2.  \"compositions\" and\n3.  \"Notes\"\n\nI am going to download the first two Excel sheets.\n\n:::::: my-r-code\n:::: my-r-code-header\n::: {#cnj-wb-download}\n: Download the World Bank classification file\n:::\n::::\n\n::: my-r-code-container\n<center>**Run this code chunk manually if the file still needs to be\ndownloaded.**</center>\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\n## create folders ###########\npb_create_folder(base::paste0(here::here(), \"/data/\"))\npb_create_folder(base::paste0(here::here(), \"/data/wb\"))\n\n## download wb-class file ##############\ndownloader::download(\n    url = \"https://datacatalogfiles.worldbank.org/ddh-published/0037712/DR0090755/CLASS.xlsx\",\n    destfile = base::paste0(here::here(), \n            \"/data/wb/wb-class.xlsx\")\n)\n\n## create R object ############\nwb_economies <- \n  readxl::read_xlsx(\n    base::paste0(here::here(), \n    \"/data/wb/wb-class.xlsx\"),\n           sheet = \"List of economies\") \n\n\nwb_compositions <- \n  readxl::read_xlsx(\n    base::paste0(here::here(), \n    \"/data/wb/wb-class.xlsx\"),\n           sheet = \"compositions\")\n\n## save as .rds files ###############\npb_save_data_file(\n  \"wb\", \n  wb_economies, \n  \"wb_economies.rds\"\n)\n\n\npb_save_data_file(\n  \"wb\", \n  wb_compositions, \n  \"wb_compositions.rds\"\n)\n```\n:::\n\n\n\n\n\n<center>(*For this R code chunk is no output available*)</center>\n:::\n::::::\n\n## Inspect World Bank Data {#sec-wb-inspect}\n\nTo get an detailed understanding of the data structures I will provide\nthe following outputs:\n\n1.  A summary statistics with `skimr::skim()` followed by inspection of\n    the value for the first rows of each column with `dplyr::glimpse()`.\n2.  Several detailed outputs of the classifications categories (regions)\n    and their elements (countries) in different code chunks (tabs).\n\n## Show Data\n\n:::::::::::::::: my-code-collection\n::::: my-code-collection-header\n::: my-code-collection-icon\n:::\n\n::: {#exm-wb-inspect}\n: Inspect the structure of the World Bank classification\n:::\n:::::\n\n:::::::::::: my-code-collection-container\n::::::::::: panel-tabset\n###### WB `economies`\n\n:::::: my-r-code\n:::: my-r-code-header\n::: {#cnj-inspect-wb-sheet1}\n: Inspect sheet `List of Economies` of the World Bank classification\nfile\n:::\n::::\n\n::: my-r-code-container\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_economies <- base::readRDS(\"data/wb/wb_economies.rds\")\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(wb_economies)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(wb_economies)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |wb_economies |\n|Number of rows           |267          |\n|Number of columns        |5            |\n|_______________________  |             |\n|Column type frequency:   |             |\n|character                |5            |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: character**\n\n|skim_variable    | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Economy          |         1|          1.00|   4|  50|     0|      266|          0|\n|Code             |         1|          1.00|   3|   3|     0|      266|          0|\n|Region           |        49|          0.82|  10|  26|     0|        7|          0|\n|Income group     |        50|          0.81|  10|  19|     0|        4|          0|\n|Lending category |       122|          0.54|   3|   5|     0|        3|          0|\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 267\n#> Columns: 5\n#> $ Economy            <chr> \"Afghanistan\", \"Albania\", \"Algeria\", \"American Samo…\n#> $ Code               <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\", \"AND\", \"AGO\", \"ATG\", \"A…\n#> $ Region             <chr> \"South Asia\", \"Europe & Central Asia\", \"Middle East…\n#> $ `Income group`     <chr> \"Low income\", \"Upper middle income\", \"Upper middle …\n#> $ `Lending category` <chr> \"IDA\", \"IBRD\", \"IBRD\", NA, NA, \"IBRD\", \"IBRD\", \"IBR…\n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::::\n\n###### WB `compositions`\n\n:::::: my-r-code\n:::: my-r-code-header\n::: {#cnj-inspect-wb-sheet2}\n: Inspect sheet `compositions` of the World Bank classification file\n:::\n::::\n\n::: my-r-code-container\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_compositions <- base::readRDS(\"data/wb/wb_compositions.rds\")\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(wb_compositions)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(wb_compositions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                |\n|:------------------------|:---------------|\n|Name                     |wb_compositions |\n|Number of rows           |2084            |\n|Number of columns        |4               |\n|_______________________  |                |\n|Column type frequency:   |                |\n|character                |4               |\n|________________________ |                |\n|Group variables          |None            |\n\n\n**Variable type: character**\n\n|skim_variable   | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:---------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|WB_Group_Code   |         0|             1|   3|   3|     0|       48|          0|\n|WB_Group_Name   |         0|             1|   5|  50|     0|       48|          0|\n|WB_Country_Code |         0|             1|   3|   3|     0|      218|          0|\n|WB_Country_Name |         0|             1|   4|  30|     0|      218|          0|\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 2,084\n#> Columns: 4\n#> $ WB_Group_Code   <chr> \"AFE\", \"AFE\", \"AFE\", \"AFE\", \"AFE\", \"AFE\", \"AFE\", \"AFE\"…\n#> $ WB_Group_Name   <chr> \"Africa Eastern and Southern\", \"Africa Eastern and Sou…\n#> $ WB_Country_Code <chr> \"AGO\", \"BWA\", \"BDI\", \"COM\", \"COD\", \"ERI\", \"SWZ\", \"ETH\"…\n#> $ WB_Country_Name <chr> \"Angola\", \"Botswana\", \"Burundi\", \"Comoros\", \"Congo, De…\n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::::\n:::::::::::\n::::::::::::\n::::::::::::::::\n\n## Description of WB Data\n\n### List of Economies\n\n::: {#cau-wb-country .callout-caution}\nThe term `country`, used interchangeably with `economy`, does not imply\npolitical independence but refers to any territory for which authorities\nreport separate social or economic statistics.\n:::\n\n#### Columns\n\nTo understand the missing data structure of the \"List of Economies\" one\nmust know that the data consists of two different tables, separated by\nan empty line (= one `NA` for all columns):\n\nThe dataset consists of 5 columns:\n\n1.  **Economy** with a list of 218 economies (= countries or areas in\n    <a class='glossary' title='The United Nations publication “Standard Country or Area Codes for Statistical Use” was originally published as Series M, No. 49 and is now commonly referred to as the M49 standard. M49 is a country/areas classification system prepared by the Statistics Division of the United Nations Secretariat primarily for use in its publications and databases.'>M49</a> language, see @sec-m49.\n2.  **Code** with the ISO-alpha3 codes for 218 countries (row 2-219) and\n    for 48 additional (regional, economical, and political) areas.\n3.  **Region** with seven different areas:\n    -   East Asia and Pacific,\n    -   Europe and Central Asia,\n    -   Latin America & the Caribbean,\n    -   Middle East and North Africa,\n    -   North America,\n    -   South Asia, and\n    -   Sub-Saharan Africa\n4.  **Income group** with four categories:\n    -   Low income,\n    -   Lower middle income,\n    -   Higher middle income, and\n    -   High income.\n5.  **Lending category** with three categories:\n    -   <a class='glossary' title='The International Bank for Reconstruction and Development (IBRD) is a global development cooperative owned by 189 member countries. As the largest development bank in the world, it supports the World Bank Group’s mission by providing loans, guarantees, risk management products, and advisory services to middle-income and creditworthy low-income countries, as well as by coordinating responses to regional and global challenges. (https://www.worldbank.org/en/who-we-are/ibrd)'>IBRD</a>,\n    -   <a class='glossary' title='Blend countries are eligible for IDA loans but are also eligible for IBRD loans because they are financially creditworthy.'>Blend</a>, and\n    -   <a class='glossary' title='The International Development Association (IDA) is the part of the World Bank that helps the world’s low-income countries. IDA’s grants and low-interest loans help countries invest in their futures, improve lives, and create safer, more prosperous communities around the world. (https://ida.worldbank.org/en/what-is-ida)'>IDA</a>\n\n#### Missing values\n\nWe have now a better understanding of the missing values structure:\n\n-   The variables `Economies` and `Code` are complete. The only one\n    missing value results from the separated empty line between the two\n    datasets.\n-   The 49 missing values in the column `Region` come from the second\n    part of the database, because all the rows from 220-267 (= 48\n    rows)are empty. Adding the missing value for the whole empty line we\n    got exactly the 49 missing values.\n-   In contrast to `Region` there is one missing value in the upper\n    (first) part of the data: The reason is that `Venezuela RB` is\n    lacking an income group because it has been temporarily unclassified\n    since July 2021 pending release of revised national accounts\n    statistics. Venezuela, RB was classified as an upper-middle income\n    country until FY21 (Fiscal Year 2021), has been unclassified since\n    then due to the unavailability of data. But it is currently again\n    classified as `Upper middle income` (See the World Bank [page about\n    Venezuela,\n    RB](https://archive.doingbusiness.org/en/data/exploreeconomies/venezuela)).\n    But this actually renewed classification is not included in the\n    somewhat older dataset from the FY2023.\n-   The many missing values in the `Lending category` reflects the fact\n    that only some countries are eligible for their development\n    supporting low money lending conditions.\n\n#### Income groups\n\nThe cut off limits for the income groups are: (from the \"Notes\" sheet)\n\n-   low income, \\$1,145 or less;\n-   lower middle income, \\$1,146 to \\$4,515;\n-   upper middle income, \\$4,516 to \\$14,005; and\n-   high income, more than \\$14,005.\n\n#### Lending categories\n\nThe three lending categories and their relation to each other are:\n\n> <a class='glossary' title='The International Development Association (IDA) is the part of the World Bank that helps the world’s low-income countries. IDA’s grants and low-interest loans help countries invest in their futures, improve lives, and create safer, more prosperous communities around the world. (https://ida.worldbank.org/en/what-is-ida)'>IDA</a> countries are those that lack the\n> financial ability to borrow from <a class='glossary' title='The International Bank for Reconstruction and Development (IBRD) is a global development cooperative owned by 189 member countries. As the largest development bank in the world, it supports the World Bank Group’s mission by providing loans, guarantees, risk management products, and advisory services to middle-income and creditworthy low-income countries, as well as by coordinating responses to regional and global challenges. (https://www.worldbank.org/en/who-we-are/ibrd)'>IBRD</a>. IDA credits are\n> deeply concessional—interest-free loans and grants for programs aimed\n> at boosting economic growth and improving living conditions. IBRD\n> loans are non-concessional. `Blend` countries are eligible for IDA\n> credits because of their low per capita incomes but are also eligible\n> for IBRD because they are financially creditworthy.\n\nThe effective operational cutoff for <a class='glossary' title='The International Development Association (IDA) is the part of the World Bank that helps the world’s low-income countries. IDA’s grants and low-interest loans help countries invest in their futures, improve lives, and create safer, more prosperous communities around the world. (https://ida.worldbank.org/en/what-is-ida)'>IDA</a>\neligibility is \\$1,335 or less.\n\n#### Miscellanous\n\nWhat follows is a quote about some details of the income classifications\nfor the 2023 file:\n\n> Set on 1 July 2022 remain in effect until 1 July 2023. Venezuela has\n> been temporarily unclassified since July 2021 pending release of\n> revised national accounts statistics. Argentina, which was temporarily\n> unclassified in July 2016 pending release of revised national accounts\n> statistics, was classified as upper middle income for FY17 as of 29\n> September 2016 based on alternative conversion factors. Also effective\n> 29 September 2016, Syrian Arab Republic is reclassified from IBRD\n> lending category to IDA-only. On 29 March 2017, new country codes were\n> introduced to align World Bank 3-letter codes with ISO 3-letter codes:\n> Andorra (AND), Dem. Rep. Congo (COD), Isle of Man (IMN), Kosovo (XKX),\n> Romania (ROU), Timor-Leste (TLS), and West Bank and Gaza (PSE). It is\n> to be noted that Venezuela, RB classified as an upper-middle income\n> country until FY21, has been unclassified since then due to the\n> unavailability of data.\n\n### Compositions\n\nThe interpretation of the `compositions` Excel sheet is more difficult,\nnot so straight forward as the `List of Economies`. The `compositions`\nsheet consists of four columns with 2084 rows.\n\n1.  `WB_Group_Code`: A three letter code similar to the ISO-alpha3 code\n    but not registered by ISO but by the World Bank.\n2.  `WB_Group_Name`: The group name assigned to a regional, economical\n    or political entity.\n3.  `WB_County_Code`: The country or area name as specified in \"List of\n    Economies\".\n4.  `WB_Country_Name`: The ISO-alpha3 code as specifies in \"List of\n    Economies\", generated and maintained by <a class='glossary' title='ISO is an independent, non-governmental international organization that develops and publishes international standards to ensure the effectiveness, efficiency, and quality of goods, services, and systems. Founded in 1947, ISO is headquartered in Geneva, Switzerland, and has over 170 member countries, each represented by its national standardization body.'>ISO</a>.\n\nThe table is easier to understand if we relocate `WB_County_Code` and\n`WB_Country_Name` to the first resp. second column. Then we can say that\nthe `compositions` sheet displays all affiliations for a country. It is\na combination of all the 49 rows of the second part in the \"List of\nEconomies\" dataset. To learn about these different groups and the\ncategorization criteria behind it is of special interest for my and the\nmain purpose why I am writing this book.\n\n### Interim Summary {#sec-wb-interim-summary}\n\nThe only missing data in the columns `Economy` and `Code` corresponds to\nthe empty line #220 that separates the country codes from the regional\ncodes. The missing data in the other columns stem from the different\nstructure of the second part (starting with row #221) of the data, which\nconsists only of the two columns 'Economy' and 'Code'.\n\nEssentially this means that we have in the `CLASS.xslx` file two\ndifferent data sets: One for economies and the other one to explicate\nregional, economical and political grouping codes. In the Excel sheet\n`compositions` you will find an extended list of all available group\nnames and their three letter codes combined with the country names and\ntheir three letter codes. These group names comprise different kinds of\nregional groups but also names and codes for different combination of\ncountry incomes and lending categories.\n\nAll these groups may be of interests for analysis of different trends.\nBut the regional (sub)groups of the `compositions` sheet do not add up\nto the complete number of countries (218). This is in contrast to the\ndifferent regional groups of the WID database because all their regional\ngroups (region1 = 5, region2 = 18, region4 = 10, and region5 = 8 groups)\nincludes all countries (in this case: 216).\n\n## Analysis of WB Data\n\nThe World Bank file `CLASS.xslx` classifies all World Bank member\ncountries (189), and all other economies with populations of more than\n30,000 (29) in a coarse grid of only seven regions[^02-world-bank-1].\nFor operational and analytical purposes, these economies are divided\namong different groups according to the criteria type, such as:\n\n- [gross national income (GNI) per\ncapita](https://datahelpdesk.worldbank.org/knowledgebase/articles/378831-why-use-gni-per-capita-to-classify-economies-into) in 2023, calculated using the [World Bank Atlas\nmethod](https://datahelpdesk.worldbank.org/knowledgebase/articles/378832-what-is-the-world-bank-atlas-method).\n- lending conditions,\n- <a class='glossary' title='Demographic dividend refers to the growth in an economy that results from a change in the age structure of a country’s population. This is typically brought on by a decline in fertility and mortality rates. (Investopedia, https://www.investopedia.com/terms/d/demographic-dividend.asp)'>demographic dividend</a>, etc.\n\n[^02-world-bank-1]: This information comes from the \"Notes\" sheet of the\n    Excel file.\n\n### Separate list of countries from \"List of Economies\"\n\nMy first action for further analysis of the data is to isolate the first data part of the \"List of Economies\" and then to use the predefined group structure in this part.\n\n::: {.my-code-collection}\n:::: {.my-code-collection-header}\n::::: {.my-code-collection-icon}\n:::::\n:::::: {#exm-wb-separate-countries}\n: Separate country data from the Excel sheet `List of Economies` \n::::::\n\n::::\n\n::::{.my-code-collection-container}\n\n::: {.panel-tabset}\n\n###### WB `economies` separated\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-economies-separated}\n: List the full data of the World Bank economies\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_clean <-  base::readRDS(\"data/wb/wb_economies.rds\") |> \n    dplyr::slice(1:218) |> \n    dplyr::mutate(`Income group` =\n           base::ifelse(base::is.na(`Income group`), \"Upper middle income\", `Income group`)\n           )\n\npb_save_data_file(\"wb\", wb_clean, \"wb_clean.rds\")\n\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(wb_clean)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(wb_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |wb_clean |\n|Number of rows           |218      |\n|Number of columns        |5        |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |5        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable    | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Economy          |         0|          1.00|   4|  30|     0|      218|          0|\n|Code             |         0|          1.00|   3|   3|     0|      218|          0|\n|Region           |         0|          1.00|  10|  26|     0|        7|          0|\n|Income group     |         0|          1.00|  10|  19|     0|        4|          0|\n|Lending category |        73|          0.67|   3|   5|     0|        3|          0|\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 218\n#> Columns: 5\n#> $ Economy            <chr> \"Afghanistan\", \"Albania\", \"Algeria\", \"American Samo…\n#> $ Code               <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\", \"AND\", \"AGO\", \"ATG\", \"A…\n#> $ Region             <chr> \"South Asia\", \"Europe & Central Asia\", \"Middle East…\n#> $ `Income group`     <chr> \"Low income\", \"Upper middle income\", \"Upper middle …\n#> $ `Lending category` <chr> \"IDA\", \"IBRD\", \"IBRD\", NA, NA, \"IBRD\", \"IBRD\", \"IBR…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::::\n:::::\n\n\n###### WB standard\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-clean-standard}\n: Show pre-defined grouping of Word Bank data\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(\n    wb_standard <- pb_class_scheme(\n            df = base::readRDS(\"data/wb/wb_clean.rds\"),\n            sel1 = rlang::quo(`Economy`),\n            sel2 = rlang::quo(`Region`)\n            )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-e728033e34b661baa7db\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e728033e34b661baa7db\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"North America\",\"South Asia\",\"Sub-Saharan Africa\"],[\"American Samoa; Australia; Brunei Darussalam; Cambodia; China; Fiji; French Polynesia; Guam; Hong Kong SAR, China; Indonesia; Japan; Kiribati; Korea, Dem. People's Rep.; Korea, Rep.; Lao PDR; Macao SAR, China; Malaysia; Marshall Islands; Micronesia, Fed. Sts.; Mongolia; Myanmar; Nauru; New Caledonia; New Zealand; Northern Mariana Islands; Palau; Papua New Guinea; Philippines; Samoa; Singapore; Solomon Islands; Taiwan, China; Thailand; Timor-Leste; Tonga; Tuvalu; Vanuatu; Vietnam ;\",\"Albania; Andorra; Armenia; Austria; Azerbaijan; Belarus; Belgium; Bosnia and Herzegovina; Bulgaria; Channel Islands; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Georgia; Germany; Gibraltar; Greece; Greenland; Hungary; Iceland; Ireland; Isle of Man; Italy; Kazakhstan; Kosovo; Kyrgyz Republic; Latvia; Liechtenstein; Lithuania; Luxembourg; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway; Poland; Portugal; Romania; Russian Federation; San Marino; Serbia; Slovak Republic; Slovenia; Spain; Sweden; Switzerland; Tajikistan; Türkiye; Turkmenistan; Ukraine; United Kingdom; Uzbekistan ;\",\"Antigua and Barbuda; Argentina; Aruba; Bahamas, The; Barbados; Belize; Bolivia; Brazil; British Virgin Islands; Cayman Islands; Chile; Colombia; Costa Rica; Cuba; Curaçao; Dominica; Dominican Republic; Ecuador; El Salvador; Grenada; Guatemala; Guyana; Haiti; Honduras; Jamaica; Mexico; Nicaragua; Panama; Paraguay; Peru; Puerto Rico; Sint Maarten (Dutch part); St. Kitts and Nevis; St. Lucia; St. Martin (French part); St. Vincent and the Grenadines; Suriname; Trinidad and Tobago; Turks and Caicos Islands; Uruguay; Venezuela, RB; Virgin Islands (U.S.) ;\",\"Algeria; Bahrain; Djibouti; Egypt, Arab Rep.; Iran, Islamic Rep.; Iraq; Israel; Jordan; Kuwait; Lebanon; Libya; Malta; Morocco; Oman; Qatar; Saudi Arabia; Syrian Arab Republic; Tunisia; United Arab Emirates; West Bank and Gaza; Yemen, Rep. ;\",\"Bermuda; Canada; United States ;\",\"Afghanistan; Bangladesh; Bhutan; India; Maldives; Nepal; Pakistan; Sri Lanka ;\",\"Angola; Benin; Botswana; Burkina Faso; Burundi; Cabo Verde; Cameroon; Central African Republic; Chad; Comoros; Congo, Dem. Rep.; Congo, Rep.; Côte d’Ivoire; Equatorial Guinea; Eritrea; Eswatini; Ethiopia; Gabon; Gambia, The; Ghana; Guinea; Guinea-Bissau; Kenya; Lesotho; Liberia; Madagascar; Malawi; Mali; Mauritania; Mauritius; Mozambique; Namibia; Niger; Nigeria; Rwanda; São Tomé and Príncipe; Senegal; Seychelles; Sierra Leone; Somalia; South Africa; South Sudan; Sudan; Tanzania; Togo; Uganda; Zambia; Zimbabwe ;\"],[38,58,42,21,3,8,48]],\"container\":\"<table class=\\\"cell-border compact stripe\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Region<\\/th>\\n      <th>Country<\\/th>\\n      <th>N<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":25,\"lengthMenu\":[5,10,15,20,25,50],\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":3},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Region\",\"targets\":1},{\"name\":\"Country\",\"targets\":2},{\"name\":\"N\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n***\n\n`Region` is a coarse classification scheme with only **7 regions formed by 218 countries**.\n\n::::\n:::::\n\n:::\n\n::::\n:::::\n\nThe \"standard\" World Bank grouping system comprises 7 groups and is therefore different to the m49 group divisions of 5 regions, 17 sub-regions and 23 intermediate regions. In contrast to the smallest UN geoscheme of 5 (resp. 6 continents with Antarctica) the WB smallest classification includes transcontinetal groupings such as `Europe and Central Asia`, `Middle East and North Africa` (<a class='glossary' title='The Middle East and North Africa (MENA) region is a statistical grouping used by the United Nations (UN) to categorize 20 countries in the region. The UN defines MENA as comprising: Bahrain, Egypt, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Oman, Qatar, Saudi Arabia, Syria, United Arab Emirates, and Yemen (Middle East). Algeria, Libya, Morocco, and Tunisia (North Africa).'>MENA</a>), `East Asia and Pacific`).\n\n\n### Differences between M49 and World Bank classification\n\nThe separation shows 218 \"Economies\", i.e. 30 rows less than the 248 countries or areas of the <a class='glossary' title='The United Nations geoscheme is a system which divides 248 countries and territories in the world into six continental regions, 22 geographical subregions, and two intermediary regions. It was devised by the United Nations Statistics Division (UNSD) based on the M49 coding classification'>United Nations geoscheme</a> (@sec-m49-display-result-1). It is vitale to understand the differences.\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-m49-wb-diff}\n: Differences between United Nations and World Bank country classifications \n::::::\n:::\n::::{.my-procedure-container}\nTo understand the differences between the UN M49 and the World Bank classification I will aplly the following procedure\n\n**Prepare datasets for the comparison (Tab: Prepare data)**\n\n1. Load the data with more rows (UN m49: `m49_clean3.rds`) into the memory and call this tibble object `df_m49`.\n2. Select the columns `ISO-alpha3 Code`, `Country or Area`, and `UN` member state for further processing.\n3. Rename the first two columns as `Code` and `UN Country`\n4. Relocate `Code` as first column\n5. Load the World Bank data `wb_clean.rds` into the memory and call this tibble object `df_wb`.\n6. Select the columns `Economy` and `Code`.\n7. Rename column `Economy` to `WB Economy`.\n\n**Compare the two datasets**\n\n8. Join both datasets by `Code` and keep all observations of `df_m49` without a match in `df_wb` (Tab: M49 vs. DB).\n9. Join both datasets by `Code` and keep all observations of `df_wb` without a match in `df_m49` (Tab: DB vs. M49)\n\n::::\n:::::\n\n\n\n::: {.my-code-collection}\n:::: {.my-code-collection-header}\n::::: {.my-code-collection-icon}\n:::::\n:::::: {#exm-m49-wb-diffs}\n: Differences of UN M49 and World Bank classification\n::::::\n\n::::\n\n::::{.my-code-collection-container}\n\n::: {.panel-tabset}\n\n###### Prepare data\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-prepare-data}\n: Prepare the datasets of UN M49 geoscheme with World Bank classification\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\ndf_un <- base::readRDS(\"data/unsd/m49_clean3.rds\") |>     # (1)\n    dplyr::select(c(1,2, UN)) |>                          # (2)\n    dplyr::rename(\n        Code = `ISO-alpha3 Code`,\n        `UN Country` = `Country or Area`\n        ) |>                                              # (3)\n    dplyr::relocate(Code, .before = `UN Country`)         # (4)\n\ndf_wb <- base::readRDS(\"data/wb/wb_clean.rds\") |>         # (5)\n    dplyr::select(1,2) |>                                 # (6)\n    dplyr::rename(`WB Economy` = Economy)                 # (7)                                       \n```\n:::\n\n\n\n\n\n<center>(*For this R code chunk is no output available*)</center>\n\n::::\n:::::\n\n\n###### M49 vs. WB\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-m49-vs-wb}\n: Show M49 rows that are not included in the World Bank classification data\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(\n    m49_wb_diff <- dplyr::anti_join(                    # (8)\n        df_un, df_wb, dplyr::join_by(Code == Code)\n        ) |> \n        DT::datatable(option = list( pageLength = 50))\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-b303c2ad95548c7b49f6\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b303c2ad95548c7b49f6\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\"],[\"AIA\",\"BES\",\"BVT\",\"IOT\",\"CXR\",\"CCK\",\"COK\",\"FLK\",\"GUF\",\"ATF\",\"GLP\",\"GGY\",\"HMD\",\"VAT\",\"JEY\",\"MTQ\",\"MYT\",\"MSR\",\"NIU\",\"NFK\",\"PCN\",\"REU\",\"BLM\",\"SHN\",\"SPM\",\"SCQ\",\"SGS\",\"SJM\",\"TKL\",\"UMI\",\"WLF\",\"ESH\",\"ALA\"],[\"Anguilla\",\"Bonaire, Sint Eustatius and Saba\",\"Bouvet Island\",\"British Indian Ocean Territory\",\"Christmas Island\",\"Cocos (Keeling) Islands\",\"Cook Islands\",\"Falkland Islands (Malvinas)\",\"French Guiana\",\"French Southern Territories\",\"Guadeloupe\",\"Guernsey\",\"Heard Island and McDonald Islands\",\"Holy See\",\"Jersey\",\"Martinique\",\"Mayotte\",\"Montserrat\",\"Niue\",\"Norfolk Island\",\"Pitcairn\",\"Réunion\",\"Saint Barthélemy\",\"Saint Helena\",\"Saint Pierre and Miquelon\",\"Sark\",\"South Georgia and the South Sandwich Islands\",\"Svalbard and Jan Mayen Islands\",\"Tokelau\",\"United States Minor Outlying Islands\",\"Wallis and Futuna Islands\",\"Western Sahara\",\"Åland Islands\"],[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Code<\\/th>\\n      <th>UN Country<\\/th>\\n      <th>UN<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":50,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":3},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Code\",\"targets\":1},{\"name\":\"UN Country\",\"targets\":2},{\"name\":\"UN\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n::::\n:::::\n\n###### WB vs. M49\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-vs-m49}\n: Show World Bank economy rows that are not included in the UN M49 classification data\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(\n    wb_m49_diff <- dplyr::anti_join(\n        df_wb, df_un, dplyr::join_by(Code == Code)      # (9)\n        ) \n)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 3 × 2\n#>   `WB Economy`    Code \n#>   <chr>           <chr>\n#> 1 Channel Islands CHI  \n#> 2 Kosovo          XKX  \n#> 3 Taiwan, China   TWN\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::::\n:::::\n\n:::\n\n::::\n:::::\n\n\n### Interim Summary\n\nThe M49 geoscheme of the United Nations is the more comprehensive classification system. It includes 33 areas more than the WB classification. But the difference between the two system is 248 - 218 = 30 and not 33 countries, because the World Bank classification contains three geographical areas that are not part of the m49 system:\n\n- Channel Islands\n- Taiwan and\n- Kosovo\n\n**Channel Islands**\n\nIn the World Bank classification system is \"Channel Islands\" sorted under `Economy` (= equivalent to `Region or Area` in the M49 taxonomy). But in the original UN notation \"Channel Island\" is an \"Intermediate Region Name\".\n\nThe biggest three of the Channels Island (Jersey, Guernsey and Sark) are already areas included in the UN M49 scheme, although Sark has not (yet?) an official ISO code. I will therefore remove the `Economy`row for \"Channel Islands\" from the World Bank data because it is also included in the M49 listing.\n\n**Taiwan (TN, TWN)**\n\nThe status of Taiwan is a disputed one:\n\n> China considers Taiwan a part of its territory and rejects any notion of Taiwanese independence. As one of the world's largest and most influential countries, China wields significant political and economic power, which can influence other nations' decisions regarding Taiwan's status. Many countries have chosen to adhere to China's \"One China\" policy, which recognizes Taiwan as a part of China rather than an independent country. ([WorldAtlas](https://www.worldatlas.com/geography/how-many-countries-are-there-in-the-world.html#h_67893363119851681224132690))\n\nBut for analytical reasons it could be interesting to analyze the well-advanced economy of Taiwan separately. I will therefore include Taiwan in my working country and area classification system.\n\n**Kosovo (XK, XKX)**\n\n> Recognizing Kosovo as an independent country has been a contentious issue in international politics for many years. While the United States has recognized Kosovo as a sovereign state since it declared independence from Serbia in 2008, other countries and international bodies do not. ([WorldAtlas](https://www.worldatlas.com/geography/how-many-countries-are-there-in-the-world.html#h_20077683018261681224123451))\n\nHere applies the same reason for inclusion of Taiwan in my my classification system: It may be interesting to analyse this region/country separately from other countries of this region.\n\n## Combining M49 and WB\n\nAs an interim conclusion (without analysis the second Excel sheet `compositions` of the World Bank classification system) I will combine the World Bank data (excluding Channel Islands) data with the UN M49 geoscheme.\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-wb-combine-m49}\n: Combine M49 with the World Bank classification\n::::::\n:::\n::::{.my-procedure-container}\n\n**Combine M49 and World Bank data and display \"Structure\" and \"Data Values\"**\n\n1. Create directory \"data/meta\" for data combined from different chapters.\n1. Load the cleaned version of the World Bank classification (\"data/wb/wb_clean.rds\")\n2. Remove the `Economy` row with the Value of \"Channel Islands\".\n3. Rename the column `Region` to `WB Region` to remind where this regional groupings comes from. \n4. Replace the NA's values of `Lending categoy` with \"NLC\" (= No Lending Category) to distinguish it from those rows of `Lending category` that have `NA`s because of a missing `Country or Area` (resp. `Economy`).\n5. Saves this new cleaned World Bank dataset as \"data/wb/wb_clean2.rds\".\n6. Load the latest cleaned version of the m49 data (\"data/unsd/m49_clean3.rds\") into memory\n7. Join the UN m49 with the World Bank dataset\n8. Remove the now redundant `Economy` column.\n9. Save the new dataset as \"data/meta/m49_ext.rds\" (\"ext\" stands for extended)\n10. Display the structure of the new dataset `m49_ext`.\n11. Display the dataset with `DT::datatable()` for explorations and further analysis. (Tab: \"Data Values\")\n\n::::\n:::::\n\n::: {.my-code-collection}\n:::: {.my-code-collection-header}\n::::: {.my-code-collection-icon}\n:::::\n:::::: {#exm-wb-combine-m49}\n: Combine and show the structure and data values of the integrated dataset\n::::::\n\n::::\n\n::::{.my-code-collection-container}\n\n::: {.panel-tabset}\n\n###### Structure\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-combine-m49-structure}\n: Show structure of the combine M49 and World Bank classification\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npb_create_folder(\"data/meta\")\n\nwb_clean2 <- base::readRDS(\"data/wb/wb_clean.rds\") |> \n    dplyr::filter(Economy != \"Channel Islands\") |> \n    dplyr::rename(`WB Region` = Region) |> \n    dplyr::mutate(`Lending category` =\n        base::ifelse(base::is.na(`Lending category`), \n                     \"NLC\", `Lending category`)\n        )\n\npb_save_data_file(\"wb\", wb_clean2, \"wb_clean2.rds\")\n\nm49_clean3 <- base::readRDS(\"data/unsd/m49_clean3.rds\")\n\nm49_ext <- dplyr::full_join(\n    m49_clean3, wb_clean2, dplyr::join_by(`ISO-alpha3 Code` == Code)\n) |> \n    dplyr::select(-Economy) |> \n    dplyr::mutate(\n      `Country or Area` =\n          base::ifelse(`ISO-alpha3 Code` == \"XKX\", \n                     \"Kosovo\", `Country or Area`),\n      `ISO-alpha2 Code`  =\n          base::ifelse(`ISO-alpha3 Code` == \"XKX\", \n                       \"XK\", `ISO-alpha2 Code`)\n        \n        ) |> \n    dplyr::mutate(\n      `Country or Area` =\n          base::ifelse(`ISO-alpha3 Code` == \"TWN\", \n                     \"Taiwan, Province of China\", `Country or Area`),\n      `ISO-alpha2 Code`  =  \n          base::ifelse(`ISO-alpha3 Code` == \"TWN\", \n                     \"TN\", `ISO-alpha2 Code`),\n        ) |> \n    dplyr::arrange(`Country or Area`)\n\npb_save_data_file(\"meta\", m49_ext, \"m49_ext.rds\")\n\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(m49_ext)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(m49_ext)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |        |\n|:------------------------|:-------|\n|Name                     |m49_ext |\n|Number of rows           |250     |\n|Number of columns        |17      |\n|_______________________  |        |\n|Column type frequency:   |        |\n|character                |13      |\n|numeric                  |4       |\n|________________________ |        |\n|Group variables          |None    |\n\n\n**Variable type: character**\n\n|skim_variable            | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|ISO-alpha3 Code          |         0|          1.00|   3|   3|     0|      250|          0|\n|Country or Area          |         0|          1.00|   4|  52|     0|      250|          0|\n|Region Code              |         2|          0.99|   3|   3|     0|        5|          0|\n|Region Name              |         2|          0.99|   4|   8|     0|        5|          0|\n|Sub-region Code          |         2|          0.99|   3|   3|     0|       17|          0|\n|Sub-region Name          |         2|          0.99|   9|  31|     0|       17|          0|\n|Intermediate Region Code |         2|          0.99|   3|   3|     0|       22|          0|\n|Intermediate Region Name |         2|          0.99|   9|  25|     0|       22|          0|\n|M49 Code                 |         2|          0.99|   3|   3|     0|      248|          0|\n|ISO-alpha2 Code          |         0|          1.00|   2|   2|     0|      249|          0|\n|WB Region                |        33|          0.87|  10|  26|     0|        7|          0|\n|Income group             |        33|          0.87|  10|  19|     0|        4|          0|\n|Lending category         |        33|          0.87|   3|   5|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate| mean|   sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|----:|----:|--:|---:|---:|---:|----:|:-----|\n|LDC           |         2|          0.99| 0.19| 0.39|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|LLDC          |         2|          0.99| 0.13| 0.34|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|SIDS          |         2|          0.99| 0.21| 0.41|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|UN            |         2|          0.99| 0.79| 0.41|  0|   1|   1|   1|    1|▂▁▁▁▇ |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 250\n#> Columns: 17\n#> $ `ISO-alpha3 Code`          <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\", \"AND\", \"AGO\", \"…\n#> $ `Country or Area`          <chr> \"Afghanistan\", \"Albania\", \"Algeria\", \"Ameri…\n#> $ `Region Code`              <chr> \"142\", \"150\", \"002\", \"009\", \"150\", \"002\", \"…\n#> $ `Region Name`              <chr> \"Asia\", \"Europe\", \"Africa\", \"Oceania\", \"Eur…\n#> $ `Sub-region Code`          <chr> \"034\", \"039\", \"015\", \"061\", \"039\", \"202\", \"…\n#> $ `Sub-region Name`          <chr> \"Southern Asia\", \"Southern Europe\", \"Northe…\n#> $ `Intermediate Region Code` <chr> \"034\", \"039\", \"015\", \"061\", \"039\", \"017\", \"…\n#> $ `Intermediate Region Name` <chr> \"Southern Asia\", \"Southern Europe\", \"Northe…\n#> $ `M49 Code`                 <chr> \"004\", \"008\", \"012\", \"016\", \"020\", \"024\", \"…\n#> $ `ISO-alpha2 Code`          <chr> \"AF\", \"AL\", \"DZ\", \"AS\", \"AD\", \"AO\", \"AI\", \"…\n#> $ LDC                        <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n#> $ LLDC                       <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0…\n#> $ SIDS                       <dbl> 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1…\n#> $ UN                         <dbl> 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1…\n#> $ `WB Region`                <chr> \"South Asia\", \"Europe & Central Asia\", \"Mid…\n#> $ `Income group`             <chr> \"Low income\", \"Upper middle income\", \"Upper…\n#> $ `Lending category`         <chr> \"IDA\", \"IBRD\", \"IBRD\", \"NLC\", \"NLC\", \"IBRD\"…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::::\n:::::\n\n\n\n\n###### Data Values\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-combine-m49-data-values}\n: Show data values of the combined M49 and World Bank classification\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(\n    m49_ext <- base::readRDS(\"data/meta/m49_ext.rds\") |> \n        DT::datatable()\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-906d3993329b46ff3044\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-906d3993329b46ff3044\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\",\"180\",\"181\",\"182\",\"183\",\"184\",\"185\",\"186\",\"187\",\"188\",\"189\",\"190\",\"191\",\"192\",\"193\",\"194\",\"195\",\"196\",\"197\",\"198\",\"199\",\"200\",\"201\",\"202\",\"203\",\"204\",\"205\",\"206\",\"207\",\"208\",\"209\",\"210\",\"211\",\"212\",\"213\",\"214\",\"215\",\"216\",\"217\",\"218\",\"219\",\"220\",\"221\",\"222\",\"223\",\"224\",\"225\",\"226\",\"227\",\"228\",\"229\",\"230\",\"231\",\"232\",\"233\",\"234\",\"235\",\"236\",\"237\",\"238\",\"239\",\"240\",\"241\",\"242\",\"243\",\"244\",\"245\",\"246\",\"247\",\"248\",\"249\",\"250\"],[\"AFG\",\"ALB\",\"DZA\",\"ASM\",\"AND\",\"AGO\",\"AIA\",\"ATG\",\"ARG\",\"ARM\",\"ABW\",\"AUS\",\"AUT\",\"AZE\",\"BHS\",\"BHR\",\"BGD\",\"BRB\",\"BLR\",\"BEL\",\"BLZ\",\"BEN\",\"BMU\",\"BTN\",\"BOL\",\"BES\",\"BIH\",\"BWA\",\"BVT\",\"BRA\",\"IOT\",\"VGB\",\"BRN\",\"BGR\",\"BFA\",\"BDI\",\"CPV\",\"KHM\",\"CMR\",\"CAN\",\"CYM\",\"CAF\",\"TCD\",\"CHL\",\"CHN\",\"HKG\",\"MAC\",\"CXR\",\"CCK\",\"COL\",\"COM\",\"COG\",\"COK\",\"CRI\",\"HRV\",\"CUB\",\"CUW\",\"CYP\",\"CZE\",\"CIV\",\"PRK\",\"COD\",\"DNK\",\"DJI\",\"DMA\",\"DOM\",\"ECU\",\"EGY\",\"SLV\",\"GNQ\",\"ERI\",\"EST\",\"SWZ\",\"ETH\",\"FLK\",\"FRO\",\"FJI\",\"FIN\",\"FRA\",\"GUF\",\"PYF\",\"ATF\",\"GAB\",\"GMB\",\"GEO\",\"DEU\",\"GHA\",\"GIB\",\"GRC\",\"GRL\",\"GRD\",\"GLP\",\"GUM\",\"GTM\",\"GGY\",\"GIN\",\"GNB\",\"GUY\",\"HTI\",\"HMD\",\"VAT\",\"HND\",\"HUN\",\"ISL\",\"IND\",\"IDN\",\"IRN\",\"IRQ\",\"IRL\",\"IMN\",\"ISR\",\"ITA\",\"JAM\",\"JPN\",\"JEY\",\"JOR\",\"KAZ\",\"KEN\",\"KIR\",\"XKX\",\"KWT\",\"KGZ\",\"LAO\",\"LVA\",\"LBN\",\"LSO\",\"LBR\",\"LBY\",\"LIE\",\"LTU\",\"LUX\",\"MDG\",\"MWI\",\"MYS\",\"MDV\",\"MLI\",\"MLT\",\"MHL\",\"MTQ\",\"MRT\",\"MUS\",\"MYT\",\"MEX\",\"FSM\",\"MCO\",\"MNG\",\"MNE\",\"MSR\",\"MAR\",\"MOZ\",\"MMR\",\"NAM\",\"NRU\",\"NPL\",\"NLD\",\"NCL\",\"NZL\",\"NIC\",\"NER\",\"NGA\",\"NIU\",\"NFK\",\"MKD\",\"MNP\",\"NOR\",\"OMN\",\"PAK\",\"PLW\",\"PAN\",\"PNG\",\"PRY\",\"PER\",\"PHL\",\"PCN\",\"POL\",\"PRT\",\"PRI\",\"QAT\",\"KOR\",\"MDA\",\"ROU\",\"RUS\",\"RWA\",\"REU\",\"BLM\",\"SHN\",\"KNA\",\"LCA\",\"MAF\",\"SPM\",\"VCT\",\"WSM\",\"SMR\",\"STP\",\"SCQ\",\"SAU\",\"SEN\",\"SRB\",\"SYC\",\"SLE\",\"SGP\",\"SXM\",\"SVK\",\"SVN\",\"SLB\",\"SOM\",\"ZAF\",\"SGS\",\"SSD\",\"ESP\",\"LKA\",\"PSE\",\"SDN\",\"SUR\",\"SJM\",\"SWE\",\"CHE\",\"SYR\",\"TWN\",\"TJK\",\"THA\",\"TLS\",\"TGO\",\"TKL\",\"TON\",\"TTO\",\"TUN\",\"TKM\",\"TCA\",\"TUV\",\"TUR\",\"UGA\",\"UKR\",\"ARE\",\"GBR\",\"TZA\",\"UMI\",\"VIR\",\"USA\",\"URY\",\"UZB\",\"VUT\",\"VEN\",\"VNM\",\"WLF\",\"ESH\",\"YEM\",\"ZMB\",\"ZWE\",\"ALA\"],[\"Afghanistan\",\"Albania\",\"Algeria\",\"American Samoa\",\"Andorra\",\"Angola\",\"Anguilla\",\"Antigua and Barbuda\",\"Argentina\",\"Armenia\",\"Aruba\",\"Australia\",\"Austria\",\"Azerbaijan\",\"Bahamas\",\"Bahrain\",\"Bangladesh\",\"Barbados\",\"Belarus\",\"Belgium\",\"Belize\",\"Benin\",\"Bermuda\",\"Bhutan\",\"Bolivia (Plurinational State of)\",\"Bonaire, Sint Eustatius and Saba\",\"Bosnia and Herzegovina\",\"Botswana\",\"Bouvet Island\",\"Brazil\",\"British Indian Ocean Territory\",\"British Virgin Islands\",\"Brunei Darussalam\",\"Bulgaria\",\"Burkina Faso\",\"Burundi\",\"Cabo Verde\",\"Cambodia\",\"Cameroon\",\"Canada\",\"Cayman Islands\",\"Central African Republic\",\"Chad\",\"Chile\",\"China\",\"China, Hong Kong Special Administrative Region\",\"China, Macao Special Administrative Region\",\"Christmas Island\",\"Cocos (Keeling) Islands\",\"Colombia\",\"Comoros\",\"Congo\",\"Cook Islands\",\"Costa Rica\",\"Croatia\",\"Cuba\",\"Curaçao\",\"Cyprus\",\"Czechia\",\"Côte d’Ivoire\",\"Democratic People's Republic of Korea\",\"Democratic Republic of the Congo\",\"Denmark\",\"Djibouti\",\"Dominica\",\"Dominican Republic\",\"Ecuador\",\"Egypt\",\"El Salvador\",\"Equatorial Guinea\",\"Eritrea\",\"Estonia\",\"Eswatini\",\"Ethiopia\",\"Falkland Islands (Malvinas)\",\"Faroe Islands\",\"Fiji\",\"Finland\",\"France\",\"French Guiana\",\"French Polynesia\",\"French Southern Territories\",\"Gabon\",\"Gambia\",\"Georgia\",\"Germany\",\"Ghana\",\"Gibraltar\",\"Greece\",\"Greenland\",\"Grenada\",\"Guadeloupe\",\"Guam\",\"Guatemala\",\"Guernsey\",\"Guinea\",\"Guinea-Bissau\",\"Guyana\",\"Haiti\",\"Heard Island and McDonald Islands\",\"Holy See\",\"Honduras\",\"Hungary\",\"Iceland\",\"India\",\"Indonesia\",\"Iran (Islamic Republic of)\",\"Iraq\",\"Ireland\",\"Isle of Man\",\"Israel\",\"Italy\",\"Jamaica\",\"Japan\",\"Jersey\",\"Jordan\",\"Kazakhstan\",\"Kenya\",\"Kiribati\",\"Kosovo\",\"Kuwait\",\"Kyrgyzstan\",\"Lao People's Democratic Republic\",\"Latvia\",\"Lebanon\",\"Lesotho\",\"Liberia\",\"Libya\",\"Liechtenstein\",\"Lithuania\",\"Luxembourg\",\"Madagascar\",\"Malawi\",\"Malaysia\",\"Maldives\",\"Mali\",\"Malta\",\"Marshall Islands\",\"Martinique\",\"Mauritania\",\"Mauritius\",\"Mayotte\",\"Mexico\",\"Micronesia (Federated States of)\",\"Monaco\",\"Mongolia\",\"Montenegro\",\"Montserrat\",\"Morocco\",\"Mozambique\",\"Myanmar\",\"Namibia\",\"Nauru\",\"Nepal\",\"Netherlands\",\"New Caledonia\",\"New Zealand\",\"Nicaragua\",\"Niger\",\"Nigeria\",\"Niue\",\"Norfolk Island\",\"North Macedonia\",\"Northern Mariana Islands\",\"Norway\",\"Oman\",\"Pakistan\",\"Palau\",\"Panama\",\"Papua New Guinea\",\"Paraguay\",\"Peru\",\"Philippines\",\"Pitcairn\",\"Poland\",\"Portugal\",\"Puerto Rico\",\"Qatar\",\"Republic of Korea\",\"Republic of Moldova\",\"Romania\",\"Russian Federation\",\"Rwanda\",\"Réunion\",\"Saint Barthélemy\",\"Saint Helena\",\"Saint Kitts and Nevis\",\"Saint Lucia\",\"Saint Martin (French Part)\",\"Saint Pierre and Miquelon\",\"Saint Vincent and the Grenadines\",\"Samoa\",\"San Marino\",\"Sao Tome and Principe\",\"Sark\",\"Saudi Arabia\",\"Senegal\",\"Serbia\",\"Seychelles\",\"Sierra Leone\",\"Singapore\",\"Sint Maarten (Dutch part)\",\"Slovakia\",\"Slovenia\",\"Solomon Islands\",\"Somalia\",\"South Africa\",\"South Georgia and the South Sandwich Islands\",\"South Sudan\",\"Spain\",\"Sri Lanka\",\"State of Palestine\",\"Sudan\",\"Suriname\",\"Svalbard and Jan Mayen Islands\",\"Sweden\",\"Switzerland\",\"Syrian Arab Republic\",\"Taiwan, Province of China\",\"Tajikistan\",\"Thailand\",\"Timor-Leste\",\"Togo\",\"Tokelau\",\"Tonga\",\"Trinidad and Tobago\",\"Tunisia\",\"Turkmenistan\",\"Turks and Caicos Islands\",\"Tuvalu\",\"Türkiye\",\"Uganda\",\"Ukraine\",\"United Arab Emirates\",\"United Kingdom of Great Britain and Northern Ireland\",\"United Republic of Tanzania\",\"United States Minor Outlying Islands\",\"United States Virgin Islands\",\"United States of America\",\"Uruguay\",\"Uzbekistan\",\"Vanuatu\",\"Venezuela (Bolivarian Republic of)\",\"Viet Nam\",\"Wallis and Futuna Islands\",\"Western Sahara\",\"Yemen\",\"Zambia\",\"Zimbabwe\",\"Åland Islands\"],[\"142\",\"150\",\"002\",\"009\",\"150\",\"002\",\"019\",\"019\",\"019\",\"142\",\"019\",\"009\",\"150\",\"142\",\"019\",\"142\",\"142\",\"019\",\"150\",\"150\",\"019\",\"002\",\"019\",\"142\",\"019\",\"019\",\"150\",\"002\",\"019\",\"019\",\"002\",\"019\",\"142\",\"150\",\"002\",\"002\",\"002\",\"142\",\"002\",\"019\",\"019\",\"002\",\"002\",\"019\",\"142\",\"142\",\"142\",\"009\",\"009\",\"019\",\"002\",\"002\",\"009\",\"019\",\"150\",\"019\",\"019\",\"142\",\"150\",\"002\",\"142\",\"002\",\"150\",\"002\",\"019\",\"019\",\"019\",\"002\",\"019\",\"002\",\"002\",\"150\",\"002\",\"002\",\"019\",\"150\",\"009\",\"150\",\"150\",\"019\",\"009\",\"002\",\"002\",\"002\",\"142\",\"150\",\"002\",\"150\",\"150\",\"019\",\"019\",\"019\",\"009\",\"019\",\"150\",\"002\",\"002\",\"019\",\"019\",\"009\",\"150\",\"019\",\"150\",\"150\",\"142\",\"142\",\"142\",\"142\",\"150\",\"150\",\"142\",\"150\",\"019\",\"142\",\"150\",\"142\",\"142\",\"002\",\"009\",null,\"142\",\"142\",\"142\",\"150\",\"142\",\"002\",\"002\",\"002\",\"150\",\"150\",\"150\",\"002\",\"002\",\"142\",\"142\",\"002\",\"150\",\"009\",\"019\",\"002\",\"002\",\"002\",\"019\",\"009\",\"150\",\"142\",\"150\",\"019\",\"002\",\"002\",\"142\",\"002\",\"009\",\"142\",\"150\",\"009\",\"009\",\"019\",\"002\",\"002\",\"009\",\"009\",\"150\",\"009\",\"150\",\"142\",\"142\",\"009\",\"019\",\"009\",\"019\",\"019\",\"142\",\"009\",\"150\",\"150\",\"019\",\"142\",\"142\",\"150\",\"150\",\"150\",\"002\",\"002\",\"019\",\"002\",\"019\",\"019\",\"019\",\"019\",\"019\",\"009\",\"150\",\"002\",\"150\",\"142\",\"002\",\"150\",\"002\",\"002\",\"142\",\"019\",\"150\",\"150\",\"009\",\"002\",\"002\",\"019\",\"002\",\"150\",\"142\",\"142\",\"002\",\"019\",\"150\",\"150\",\"150\",\"142\",null,\"142\",\"142\",\"142\",\"002\",\"009\",\"009\",\"019\",\"002\",\"142\",\"019\",\"009\",\"142\",\"002\",\"150\",\"142\",\"150\",\"002\",\"009\",\"019\",\"019\",\"019\",\"142\",\"009\",\"019\",\"142\",\"009\",\"002\",\"142\",\"002\",\"002\",\"150\"],[\"Asia\",\"Europe\",\"Africa\",\"Oceania\",\"Europe\",\"Africa\",\"Americas\",\"Americas\",\"Americas\",\"Asia\",\"Americas\",\"Oceania\",\"Europe\",\"Asia\",\"Americas\",\"Asia\",\"Asia\",\"Americas\",\"Europe\",\"Europe\",\"Americas\",\"Africa\",\"Americas\",\"Asia\",\"Americas\",\"Americas\",\"Europe\",\"Africa\",\"Americas\",\"Americas\",\"Africa\",\"Americas\",\"Asia\",\"Europe\",\"Africa\",\"Africa\",\"Africa\",\"Asia\",\"Africa\",\"Americas\",\"Americas\",\"Africa\",\"Africa\",\"Americas\",\"Asia\",\"Asia\",\"Asia\",\"Oceania\",\"Oceania\",\"Americas\",\"Africa\",\"Africa\",\"Oceania\",\"Americas\",\"Europe\",\"Americas\",\"Americas\",\"Asia\",\"Europe\",\"Africa\",\"Asia\",\"Africa\",\"Europe\",\"Africa\",\"Americas\",\"Americas\",\"Americas\",\"Africa\",\"Americas\",\"Africa\",\"Africa\",\"Europe\",\"Africa\",\"Africa\",\"Americas\",\"Europe\",\"Oceania\",\"Europe\",\"Europe\",\"Americas\",\"Oceania\",\"Africa\",\"Africa\",\"Africa\",\"Asia\",\"Europe\",\"Africa\",\"Europe\",\"Europe\",\"Americas\",\"Americas\",\"Americas\",\"Oceania\",\"Americas\",\"Europe\",\"Africa\",\"Africa\",\"Americas\",\"Americas\",\"Oceania\",\"Europe\",\"Americas\",\"Europe\",\"Europe\",\"Asia\",\"Asia\",\"Asia\",\"Asia\",\"Europe\",\"Europe\",\"Asia\",\"Europe\",\"Americas\",\"Asia\",\"Europe\",\"Asia\",\"Asia\",\"Africa\",\"Oceania\",null,\"Asia\",\"Asia\",\"Asia\",\"Europe\",\"Asia\",\"Africa\",\"Africa\",\"Africa\",\"Europe\",\"Europe\",\"Europe\",\"Africa\",\"Africa\",\"Asia\",\"Asia\",\"Africa\",\"Europe\",\"Oceania\",\"Americas\",\"Africa\",\"Africa\",\"Africa\",\"Americas\",\"Oceania\",\"Europe\",\"Asia\",\"Europe\",\"Americas\",\"Africa\",\"Africa\",\"Asia\",\"Africa\",\"Oceania\",\"Asia\",\"Europe\",\"Oceania\",\"Oceania\",\"Americas\",\"Africa\",\"Africa\",\"Oceania\",\"Oceania\",\"Europe\",\"Oceania\",\"Europe\",\"Asia\",\"Asia\",\"Oceania\",\"Americas\",\"Oceania\",\"Americas\",\"Americas\",\"Asia\",\"Oceania\",\"Europe\",\"Europe\",\"Americas\",\"Asia\",\"Asia\",\"Europe\",\"Europe\",\"Europe\",\"Africa\",\"Africa\",\"Americas\",\"Africa\",\"Americas\",\"Americas\",\"Americas\",\"Americas\",\"Americas\",\"Oceania\",\"Europe\",\"Africa\",\"Europe\",\"Asia\",\"Africa\",\"Europe\",\"Africa\",\"Africa\",\"Asia\",\"Americas\",\"Europe\",\"Europe\",\"Oceania\",\"Africa\",\"Africa\",\"Americas\",\"Africa\",\"Europe\",\"Asia\",\"Asia\",\"Africa\",\"Americas\",\"Europe\",\"Europe\",\"Europe\",\"Asia\",null,\"Asia\",\"Asia\",\"Asia\",\"Africa\",\"Oceania\",\"Oceania\",\"Americas\",\"Africa\",\"Asia\",\"Americas\",\"Oceania\",\"Asia\",\"Africa\",\"Europe\",\"Asia\",\"Europe\",\"Africa\",\"Oceania\",\"Americas\",\"Americas\",\"Americas\",\"Asia\",\"Oceania\",\"Americas\",\"Asia\",\"Oceania\",\"Africa\",\"Asia\",\"Africa\",\"Africa\",\"Europe\"],[\"034\",\"039\",\"015\",\"061\",\"039\",\"202\",\"419\",\"419\",\"419\",\"145\",\"419\",\"053\",\"155\",\"145\",\"419\",\"145\",\"034\",\"419\",\"151\",\"155\",\"419\",\"202\",\"021\",\"034\",\"419\",\"419\",\"039\",\"202\",\"419\",\"419\",\"202\",\"419\",\"035\",\"151\",\"202\",\"202\",\"202\",\"035\",\"202\",\"021\",\"419\",\"202\",\"202\",\"419\",\"030\",\"030\",\"030\",\"053\",\"053\",\"419\",\"202\",\"202\",\"061\",\"419\",\"039\",\"419\",\"419\",\"145\",\"151\",\"202\",\"030\",\"202\",\"154\",\"202\",\"419\",\"419\",\"419\",\"015\",\"419\",\"202\",\"202\",\"154\",\"202\",\"202\",\"419\",\"154\",\"054\",\"154\",\"155\",\"419\",\"061\",\"202\",\"202\",\"202\",\"145\",\"155\",\"202\",\"039\",\"039\",\"021\",\"419\",\"419\",\"057\",\"419\",\"154\",\"202\",\"202\",\"419\",\"419\",\"053\",\"039\",\"419\",\"151\",\"154\",\"034\",\"035\",\"034\",\"145\",\"154\",\"154\",\"145\",\"039\",\"419\",\"030\",\"154\",\"145\",\"143\",\"202\",\"057\",null,\"145\",\"143\",\"035\",\"154\",\"145\",\"202\",\"202\",\"015\",\"155\",\"154\",\"155\",\"202\",\"202\",\"035\",\"034\",\"202\",\"039\",\"057\",\"419\",\"202\",\"202\",\"202\",\"419\",\"057\",\"155\",\"030\",\"039\",\"419\",\"015\",\"202\",\"035\",\"202\",\"057\",\"034\",\"155\",\"054\",\"053\",\"419\",\"202\",\"202\",\"061\",\"053\",\"039\",\"057\",\"154\",\"145\",\"034\",\"057\",\"419\",\"054\",\"419\",\"419\",\"035\",\"061\",\"151\",\"039\",\"419\",\"145\",\"030\",\"151\",\"151\",\"151\",\"202\",\"202\",\"419\",\"202\",\"419\",\"419\",\"419\",\"021\",\"419\",\"061\",\"039\",\"202\",\"154\",\"145\",\"202\",\"039\",\"202\",\"202\",\"035\",\"419\",\"151\",\"039\",\"054\",\"202\",\"202\",\"419\",\"202\",\"039\",\"034\",\"145\",\"015\",\"419\",\"154\",\"154\",\"155\",\"145\",null,\"143\",\"035\",\"035\",\"202\",\"061\",\"061\",\"419\",\"015\",\"143\",\"419\",\"061\",\"145\",\"202\",\"151\",\"145\",\"154\",\"202\",\"057\",\"419\",\"021\",\"419\",\"143\",\"054\",\"419\",\"035\",\"061\",\"015\",\"145\",\"202\",\"202\",\"154\"],[\"Southern Asia\",\"Southern Europe\",\"Northern Africa\",\"Polynesia\",\"Southern Europe\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Western Asia\",\"Latin America and the Caribbean\",\"Australia and New Zealand\",\"Western Europe\",\"Western Asia\",\"Latin America and the Caribbean\",\"Western Asia\",\"Southern Asia\",\"Latin America and the Caribbean\",\"Eastern Europe\",\"Western Europe\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Northern America\",\"Southern Asia\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Southern Europe\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"South-eastern Asia\",\"Eastern Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"South-eastern Asia\",\"Sub-Saharan Africa\",\"Northern America\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Eastern Asia\",\"Eastern Asia\",\"Eastern Asia\",\"Australia and New Zealand\",\"Australia and New Zealand\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Polynesia\",\"Latin America and the Caribbean\",\"Southern Europe\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Western Asia\",\"Eastern Europe\",\"Sub-Saharan Africa\",\"Eastern Asia\",\"Sub-Saharan Africa\",\"Northern Europe\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Northern Africa\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Northern Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Northern Europe\",\"Melanesia\",\"Northern Europe\",\"Western Europe\",\"Latin America and the Caribbean\",\"Polynesia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Western Asia\",\"Western Europe\",\"Sub-Saharan Africa\",\"Southern Europe\",\"Southern Europe\",\"Northern America\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Micronesia\",\"Latin America and the Caribbean\",\"Northern Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Australia and New Zealand\",\"Southern Europe\",\"Latin America and the Caribbean\",\"Eastern Europe\",\"Northern Europe\",\"Southern Asia\",\"South-eastern Asia\",\"Southern Asia\",\"Western Asia\",\"Northern Europe\",\"Northern Europe\",\"Western Asia\",\"Southern Europe\",\"Latin America and the Caribbean\",\"Eastern Asia\",\"Northern Europe\",\"Western Asia\",\"Central Asia\",\"Sub-Saharan Africa\",\"Micronesia\",null,\"Western Asia\",\"Central Asia\",\"South-eastern Asia\",\"Northern Europe\",\"Western Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Northern Africa\",\"Western Europe\",\"Northern Europe\",\"Western Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"South-eastern Asia\",\"Southern Asia\",\"Sub-Saharan Africa\",\"Southern Europe\",\"Micronesia\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Micronesia\",\"Western Europe\",\"Eastern Asia\",\"Southern Europe\",\"Latin America and the Caribbean\",\"Northern Africa\",\"Sub-Saharan Africa\",\"South-eastern Asia\",\"Sub-Saharan Africa\",\"Micronesia\",\"Southern Asia\",\"Western Europe\",\"Melanesia\",\"Australia and New Zealand\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Polynesia\",\"Australia and New Zealand\",\"Southern Europe\",\"Micronesia\",\"Northern Europe\",\"Western Asia\",\"Southern Asia\",\"Micronesia\",\"Latin America and the Caribbean\",\"Melanesia\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"South-eastern Asia\",\"Polynesia\",\"Eastern Europe\",\"Southern Europe\",\"Latin America and the Caribbean\",\"Western Asia\",\"Eastern Asia\",\"Eastern Europe\",\"Eastern Europe\",\"Eastern Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Latin America and the Caribbean\",\"Northern America\",\"Latin America and the Caribbean\",\"Polynesia\",\"Southern Europe\",\"Sub-Saharan Africa\",\"Northern Europe\",\"Western Asia\",\"Sub-Saharan Africa\",\"Southern Europe\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"South-eastern Asia\",\"Latin America and the Caribbean\",\"Eastern Europe\",\"Southern Europe\",\"Melanesia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America and the Caribbean\",\"Sub-Saharan Africa\",\"Southern Europe\",\"Southern Asia\",\"Western Asia\",\"Northern Africa\",\"Latin America and the Caribbean\",\"Northern Europe\",\"Northern Europe\",\"Western Europe\",\"Western Asia\",null,\"Central Asia\",\"South-eastern Asia\",\"South-eastern Asia\",\"Sub-Saharan Africa\",\"Polynesia\",\"Polynesia\",\"Latin America and the Caribbean\",\"Northern Africa\",\"Central Asia\",\"Latin America and the Caribbean\",\"Polynesia\",\"Western Asia\",\"Sub-Saharan Africa\",\"Eastern Europe\",\"Western Asia\",\"Northern Europe\",\"Sub-Saharan Africa\",\"Micronesia\",\"Latin America and the Caribbean\",\"Northern America\",\"Latin America and the Caribbean\",\"Central Asia\",\"Melanesia\",\"Latin America and the Caribbean\",\"South-eastern Asia\",\"Polynesia\",\"Northern Africa\",\"Western Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Northern Europe\"],[\"034\",\"039\",\"015\",\"061\",\"039\",\"017\",\"029\",\"029\",\"005\",\"145\",\"029\",\"053\",\"155\",\"145\",\"029\",\"145\",\"034\",\"029\",\"151\",\"155\",\"013\",\"011\",\"021\",\"034\",\"005\",\"029\",\"039\",\"018\",\"005\",\"005\",\"014\",\"029\",\"035\",\"151\",\"011\",\"014\",\"011\",\"035\",\"017\",\"021\",\"029\",\"017\",\"017\",\"005\",\"030\",\"030\",\"030\",\"053\",\"053\",\"005\",\"014\",\"017\",\"061\",\"013\",\"039\",\"029\",\"029\",\"145\",\"151\",\"011\",\"030\",\"017\",\"154\",\"014\",\"029\",\"029\",\"005\",\"015\",\"013\",\"017\",\"014\",\"154\",\"018\",\"014\",\"005\",\"154\",\"054\",\"154\",\"155\",\"005\",\"061\",\"014\",\"017\",\"011\",\"145\",\"155\",\"011\",\"039\",\"039\",\"021\",\"029\",\"029\",\"057\",\"013\",\"154\",\"011\",\"011\",\"005\",\"029\",\"053\",\"039\",\"013\",\"151\",\"154\",\"034\",\"035\",\"034\",\"145\",\"154\",\"154\",\"145\",\"039\",\"029\",\"030\",\"154\",\"145\",\"143\",\"014\",\"057\",null,\"145\",\"143\",\"035\",\"154\",\"145\",\"018\",\"011\",\"015\",\"155\",\"154\",\"155\",\"014\",\"014\",\"035\",\"034\",\"011\",\"039\",\"057\",\"029\",\"011\",\"014\",\"014\",\"013\",\"057\",\"155\",\"030\",\"039\",\"029\",\"015\",\"014\",\"035\",\"018\",\"057\",\"034\",\"155\",\"054\",\"053\",\"013\",\"011\",\"011\",\"061\",\"053\",\"039\",\"057\",\"154\",\"145\",\"034\",\"057\",\"013\",\"054\",\"005\",\"005\",\"035\",\"061\",\"151\",\"039\",\"029\",\"145\",\"030\",\"151\",\"151\",\"151\",\"014\",\"014\",\"029\",\"011\",\"029\",\"029\",\"029\",\"021\",\"029\",\"061\",\"039\",\"017\",\"154\",\"145\",\"011\",\"039\",\"014\",\"011\",\"035\",\"029\",\"151\",\"039\",\"054\",\"014\",\"018\",\"005\",\"014\",\"039\",\"034\",\"145\",\"015\",\"005\",\"154\",\"154\",\"155\",\"145\",null,\"143\",\"035\",\"035\",\"011\",\"061\",\"061\",\"029\",\"015\",\"143\",\"029\",\"061\",\"145\",\"014\",\"151\",\"145\",\"154\",\"014\",\"057\",\"029\",\"021\",\"005\",\"143\",\"054\",\"005\",\"035\",\"061\",\"015\",\"145\",\"014\",\"014\",\"154\"],[\"Southern Asia\",\"Southern Europe\",\"Northern Africa\",\"Polynesia\",\"Southern Europe\",\"Middle Africa\",\"Caribbean\",\"Caribbean\",\"South America\",\"Western Asia\",\"Caribbean\",\"Australia and New Zealand\",\"Western Europe\",\"Western Asia\",\"Caribbean\",\"Western Asia\",\"Southern Asia\",\"Caribbean\",\"Eastern Europe\",\"Western Europe\",\"Central America\",\"Western Africa\",\"Northern America\",\"Southern Asia\",\"South America\",\"Caribbean\",\"Southern Europe\",\"Southern Africa\",\"South America\",\"South America\",\"Eastern Africa\",\"Caribbean\",\"South-eastern Asia\",\"Eastern Europe\",\"Western Africa\",\"Eastern Africa\",\"Western Africa\",\"South-eastern Asia\",\"Middle Africa\",\"Northern America\",\"Caribbean\",\"Middle Africa\",\"Middle Africa\",\"South America\",\"Eastern Asia\",\"Eastern Asia\",\"Eastern Asia\",\"Australia and New Zealand\",\"Australia and New Zealand\",\"South America\",\"Eastern Africa\",\"Middle Africa\",\"Polynesia\",\"Central America\",\"Southern Europe\",\"Caribbean\",\"Caribbean\",\"Western Asia\",\"Eastern Europe\",\"Western Africa\",\"Eastern Asia\",\"Middle Africa\",\"Northern Europe\",\"Eastern Africa\",\"Caribbean\",\"Caribbean\",\"South America\",\"Northern Africa\",\"Central America\",\"Middle Africa\",\"Eastern Africa\",\"Northern Europe\",\"Southern Africa\",\"Eastern Africa\",\"South America\",\"Northern Europe\",\"Melanesia\",\"Northern Europe\",\"Western Europe\",\"South America\",\"Polynesia\",\"Eastern Africa\",\"Middle Africa\",\"Western Africa\",\"Western Asia\",\"Western Europe\",\"Western Africa\",\"Southern Europe\",\"Southern Europe\",\"Northern America\",\"Caribbean\",\"Caribbean\",\"Micronesia\",\"Central America\",\"Northern Europe\",\"Western Africa\",\"Western Africa\",\"South America\",\"Caribbean\",\"Australia and New Zealand\",\"Southern Europe\",\"Central America\",\"Eastern Europe\",\"Northern Europe\",\"Southern Asia\",\"South-eastern Asia\",\"Southern Asia\",\"Western Asia\",\"Northern Europe\",\"Northern Europe\",\"Western Asia\",\"Southern Europe\",\"Caribbean\",\"Eastern Asia\",\"Northern Europe\",\"Western Asia\",\"Central Asia\",\"Eastern Africa\",\"Micronesia\",null,\"Western Asia\",\"Central Asia\",\"South-eastern Asia\",\"Northern Europe\",\"Western Asia\",\"Southern Africa\",\"Western Africa\",\"Northern Africa\",\"Western Europe\",\"Northern Europe\",\"Western Europe\",\"Eastern Africa\",\"Eastern Africa\",\"South-eastern Asia\",\"Southern Asia\",\"Western Africa\",\"Southern Europe\",\"Micronesia\",\"Caribbean\",\"Western Africa\",\"Eastern Africa\",\"Eastern Africa\",\"Central America\",\"Micronesia\",\"Western Europe\",\"Eastern Asia\",\"Southern Europe\",\"Caribbean\",\"Northern Africa\",\"Eastern Africa\",\"South-eastern Asia\",\"Southern Africa\",\"Micronesia\",\"Southern Asia\",\"Western Europe\",\"Melanesia\",\"Australia and New Zealand\",\"Central America\",\"Western Africa\",\"Western Africa\",\"Polynesia\",\"Australia and New Zealand\",\"Southern Europe\",\"Micronesia\",\"Northern Europe\",\"Western Asia\",\"Southern Asia\",\"Micronesia\",\"Central America\",\"Melanesia\",\"South America\",\"South America\",\"South-eastern Asia\",\"Polynesia\",\"Eastern Europe\",\"Southern Europe\",\"Caribbean\",\"Western Asia\",\"Eastern Asia\",\"Eastern Europe\",\"Eastern Europe\",\"Eastern Europe\",\"Eastern Africa\",\"Eastern Africa\",\"Caribbean\",\"Western Africa\",\"Caribbean\",\"Caribbean\",\"Caribbean\",\"Northern America\",\"Caribbean\",\"Polynesia\",\"Southern Europe\",\"Middle Africa\",\"Northern Europe\",\"Western Asia\",\"Western Africa\",\"Southern Europe\",\"Eastern Africa\",\"Western Africa\",\"South-eastern Asia\",\"Caribbean\",\"Eastern Europe\",\"Southern Europe\",\"Melanesia\",\"Eastern Africa\",\"Southern Africa\",\"South America\",\"Eastern Africa\",\"Southern Europe\",\"Southern Asia\",\"Western Asia\",\"Northern Africa\",\"South America\",\"Northern Europe\",\"Northern Europe\",\"Western Europe\",\"Western Asia\",null,\"Central Asia\",\"South-eastern Asia\",\"South-eastern Asia\",\"Western Africa\",\"Polynesia\",\"Polynesia\",\"Caribbean\",\"Northern Africa\",\"Central Asia\",\"Caribbean\",\"Polynesia\",\"Western Asia\",\"Eastern Africa\",\"Eastern Europe\",\"Western Asia\",\"Northern Europe\",\"Eastern Africa\",\"Micronesia\",\"Caribbean\",\"Northern America\",\"South America\",\"Central Asia\",\"Melanesia\",\"South America\",\"South-eastern Asia\",\"Polynesia\",\"Northern Africa\",\"Western Asia\",\"Eastern Africa\",\"Eastern Africa\",\"Northern Europe\"],[\"004\",\"008\",\"012\",\"016\",\"020\",\"024\",\"660\",\"028\",\"032\",\"051\",\"533\",\"036\",\"040\",\"031\",\"044\",\"048\",\"050\",\"052\",\"112\",\"056\",\"084\",\"204\",\"060\",\"064\",\"068\",\"535\",\"070\",\"072\",\"074\",\"076\",\"086\",\"092\",\"096\",\"100\",\"854\",\"108\",\"132\",\"116\",\"120\",\"124\",\"136\",\"140\",\"148\",\"152\",\"156\",\"344\",\"446\",\"162\",\"166\",\"170\",\"174\",\"178\",\"184\",\"188\",\"191\",\"192\",\"531\",\"196\",\"203\",\"384\",\"408\",\"180\",\"208\",\"262\",\"212\",\"214\",\"218\",\"818\",\"222\",\"226\",\"232\",\"233\",\"748\",\"231\",\"238\",\"234\",\"242\",\"246\",\"250\",\"254\",\"258\",\"260\",\"266\",\"270\",\"268\",\"276\",\"288\",\"292\",\"300\",\"304\",\"308\",\"312\",\"316\",\"320\",\"831\",\"324\",\"624\",\"328\",\"332\",\"334\",\"336\",\"340\",\"348\",\"352\",\"356\",\"360\",\"364\",\"368\",\"372\",\"833\",\"376\",\"380\",\"388\",\"392\",\"832\",\"400\",\"398\",\"404\",\"296\",null,\"414\",\"417\",\"418\",\"428\",\"422\",\"426\",\"430\",\"434\",\"438\",\"440\",\"442\",\"450\",\"454\",\"458\",\"462\",\"466\",\"470\",\"584\",\"474\",\"478\",\"480\",\"175\",\"484\",\"583\",\"492\",\"496\",\"499\",\"500\",\"504\",\"508\",\"104\",\"516\",\"520\",\"524\",\"528\",\"540\",\"554\",\"558\",\"562\",\"566\",\"570\",\"574\",\"807\",\"580\",\"578\",\"512\",\"586\",\"585\",\"591\",\"598\",\"600\",\"604\",\"608\",\"612\",\"616\",\"620\",\"630\",\"634\",\"410\",\"498\",\"642\",\"643\",\"646\",\"638\",\"652\",\"654\",\"659\",\"662\",\"663\",\"666\",\"670\",\"882\",\"674\",\"678\",\"680\",\"682\",\"686\",\"688\",\"690\",\"694\",\"702\",\"534\",\"703\",\"705\",\"090\",\"706\",\"710\",\"239\",\"728\",\"724\",\"144\",\"275\",\"729\",\"740\",\"744\",\"752\",\"756\",\"760\",null,\"762\",\"764\",\"626\",\"768\",\"772\",\"776\",\"780\",\"788\",\"795\",\"796\",\"798\",\"792\",\"800\",\"804\",\"784\",\"826\",\"834\",\"581\",\"850\",\"840\",\"858\",\"860\",\"548\",\"862\",\"704\",\"876\",\"732\",\"887\",\"894\",\"716\",\"248\"],[\"AF\",\"AL\",\"DZ\",\"AS\",\"AD\",\"AO\",\"AI\",\"AG\",\"AR\",\"AM\",\"AW\",\"AU\",\"AT\",\"AZ\",\"BS\",\"BH\",\"BD\",\"BB\",\"BY\",\"BE\",\"BZ\",\"BJ\",\"BM\",\"BT\",\"BO\",\"BQ\",\"BA\",\"BW\",\"BV\",\"BR\",\"IO\",\"VG\",\"BN\",\"BG\",\"BF\",\"BI\",\"CV\",\"KH\",\"CM\",\"CA\",\"KY\",\"CF\",\"TD\",\"CL\",\"CN\",\"HK\",\"MO\",\"CX\",\"CC\",\"CO\",\"KM\",\"CG\",\"CK\",\"CR\",\"HR\",\"CU\",\"CW\",\"CY\",\"CZ\",\"CI\",\"KP\",\"CD\",\"DK\",\"DJ\",\"DM\",\"DO\",\"EC\",\"EG\",\"SV\",\"GQ\",\"ER\",\"EE\",\"SZ\",\"ET\",\"FK\",\"FO\",\"FJ\",\"FI\",\"FR\",\"GF\",\"PF\",\"TF\",\"GA\",\"GM\",\"GE\",\"DE\",\"GH\",\"GI\",\"GR\",\"GL\",\"GD\",\"GP\",\"GU\",\"GT\",\"GG\",\"GN\",\"GW\",\"GY\",\"HT\",\"HM\",\"VA\",\"HN\",\"HU\",\"IS\",\"IN\",\"ID\",\"IR\",\"IQ\",\"IE\",\"IM\",\"IL\",\"IT\",\"JM\",\"JP\",\"JE\",\"JO\",\"KZ\",\"KE\",\"KI\",\"XK\",\"KW\",\"KG\",\"LA\",\"LV\",\"LB\",\"LS\",\"LR\",\"LY\",\"LI\",\"LT\",\"LU\",\"MG\",\"MW\",\"MY\",\"MV\",\"ML\",\"MT\",\"MH\",\"MQ\",\"MR\",\"MU\",\"YT\",\"MX\",\"FM\",\"MC\",\"MN\",\"ME\",\"MS\",\"MA\",\"MZ\",\"MM\",\"NA\",\"NR\",\"NP\",\"NL\",\"NC\",\"NZ\",\"NI\",\"NE\",\"NG\",\"NU\",\"NF\",\"MK\",\"MP\",\"NO\",\"OM\",\"PK\",\"PW\",\"PA\",\"PG\",\"PY\",\"PE\",\"PH\",\"PN\",\"PL\",\"PT\",\"PR\",\"QA\",\"KR\",\"MD\",\"RO\",\"RU\",\"RW\",\"RE\",\"BL\",\"SH\",\"KN\",\"LC\",\"MF\",\"PM\",\"VC\",\"WS\",\"SM\",\"ST\",\"CQ\",\"SA\",\"SN\",\"RS\",\"SC\",\"SL\",\"SG\",\"SX\",\"SK\",\"SI\",\"SB\",\"SO\",\"ZA\",\"GS\",\"SS\",\"ES\",\"LK\",\"PS\",\"SD\",\"SR\",\"SJ\",\"SE\",\"CH\",\"SY\",\"TN\",\"TJ\",\"TH\",\"TL\",\"TG\",\"TK\",\"TO\",\"TT\",\"TN\",\"TM\",\"TC\",\"TV\",\"TR\",\"UG\",\"UA\",\"AE\",\"GB\",\"TZ\",\"UM\",\"VI\",\"US\",\"UY\",\"UZ\",\"VU\",\"VE\",\"VN\",\"WF\",\"EH\",\"YE\",\"ZM\",\"ZW\",\"AX\"],[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,null,0,0,1,0,0,1,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,null,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0],[1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,null,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,null,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0],[0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,null,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,null,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0],[1,1,1,0,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,0,1,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,1,1,1,1,1,0,1,0,1,0,0,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,0,0,0,1,1,0,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,null,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,0],[\"South Asia\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",null,\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"South Asia\",\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Sub-Saharan Africa\",\"North America\",\"South Asia\",\"Latin America &amp; Caribbean\",null,\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",null,\"Latin America &amp; Caribbean\",null,\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"Sub-Saharan Africa\",\"North America\",\"Latin America &amp; Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"East Asia &amp; Pacific\",\"East Asia &amp; Pacific\",null,null,\"Latin America &amp; Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null,\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"Latin America &amp; Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null,\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",null,\"East Asia &amp; Pacific\",null,\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",null,\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",null,\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",null,null,\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"South Asia\",\"East Asia &amp; Pacific\",\"Middle East &amp; North Africa\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",null,\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"South Asia\",\"Sub-Saharan Africa\",\"Middle East &amp; North Africa\",\"East Asia &amp; Pacific\",null,\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null,\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",null,\"Middle East &amp; North Africa\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"South Asia\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null,null,\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"South Asia\",\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",null,\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",null,null,null,\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",\"Latin America &amp; Caribbean\",null,\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",null,\"Middle East &amp; North Africa\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null,\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"South Asia\",\"Middle East &amp; North Africa\",\"Sub-Saharan Africa\",\"Latin America &amp; Caribbean\",null,\"Europe &amp; Central Asia\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"East Asia &amp; Pacific\",\"Sub-Saharan Africa\",null,\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",\"Europe &amp; Central Asia\",\"Middle East &amp; North Africa\",\"Europe &amp; Central Asia\",\"Sub-Saharan Africa\",null,\"Latin America &amp; Caribbean\",\"North America\",\"Latin America &amp; Caribbean\",\"Europe &amp; Central Asia\",\"East Asia &amp; Pacific\",\"Latin America &amp; Caribbean\",\"East Asia &amp; Pacific\",null,null,\"Middle East &amp; North Africa\",\"Sub-Saharan Africa\",\"Sub-Saharan Africa\",null],[\"Low income\",\"Upper middle income\",\"Upper middle income\",\"High income\",\"High income\",\"Lower middle income\",null,\"High income\",\"Upper middle income\",\"Upper middle income\",\"High income\",\"High income\",\"High income\",\"Upper middle income\",\"High income\",\"High income\",\"Lower middle income\",\"High income\",\"Upper middle income\",\"High income\",\"Upper middle income\",\"Lower middle income\",\"High income\",\"Lower middle income\",\"Lower middle income\",null,\"Upper middle income\",\"Upper middle income\",null,\"Upper middle income\",null,\"High income\",\"High income\",\"High income\",\"Low income\",\"Low income\",\"Lower middle income\",\"Lower middle income\",\"Lower middle income\",\"High income\",\"High income\",\"Low income\",\"Low income\",\"High income\",\"Upper middle income\",\"High income\",\"High income\",null,null,\"Upper middle income\",\"Lower middle income\",\"Lower middle income\",null,\"Upper middle income\",\"High income\",\"Upper middle income\",\"High income\",\"High income\",\"High income\",\"Lower middle income\",\"Low income\",\"Low income\",\"High income\",\"Lower middle income\",\"Upper middle income\",\"Upper middle income\",\"Upper middle income\",\"Lower middle income\",\"Upper middle income\",\"Upper middle income\",\"Low income\",\"High income\",\"Lower middle income\",\"Low income\",null,\"High income\",\"Upper middle income\",\"High income\",\"High income\",null,\"High income\",null,\"Upper middle income\",\"Low income\",\"Upper middle income\",\"High income\",\"Lower middle income\",\"High income\",\"High income\",\"High income\",\"Upper middle income\",null,\"High income\",\"Upper middle income\",null,\"Lower middle income\",\"Low income\",\"High income\",\"Lower middle income\",null,null,\"Lower middle income\",\"High income\",\"High income\",\"Lower middle income\",\"Upper middle income\",\"Upper middle income\",\"Upper middle income\",\"High income\",\"High income\",\"High income\",\"High income\",\"Upper middle income\",\"High income\",null,\"Lower middle income\",\"Upper middle income\",\"Lower middle income\",\"Lower middle income\",\"Upper middle income\",\"High income\",\"Lower middle income\",\"Lower middle income\",\"High income\",\"Lower middle income\",\"Lower middle income\",\"Low income\",\"Upper middle income\",\"High income\",\"High income\",\"High income\",\"Low income\",\"Low income\",\"Upper middle income\",\"Upper middle income\",\"Low income\",\"High income\",\"Upper middle income\",null,\"Lower middle income\",\"Upper middle income\",null,\"Upper middle income\",\"Lower middle income\",\"High income\",\"Upper middle income\",\"Upper middle income\",null,\"Lower middle income\",\"Low income\",\"Lower middle income\",\"Upper middle income\",\"High income\",\"Lower middle income\",\"High income\",\"High income\",\"High income\",\"Lower middle income\",\"Low income\",\"Lower middle income\",null,null,\"Upper middle income\",\"High income\",\"High income\",\"High income\",\"Lower middle income\",\"High income\",\"High income\",\"Lower middle income\",\"Upper middle income\",\"Upper middle income\",\"Lower middle income\",null,\"High income\",\"High income\",\"High income\",\"High income\",\"High income\",\"Upper middle income\",\"High income\",\"High income\",\"Low income\",null,null,null,\"High income\",\"Upper middle income\",\"High income\",null,\"Upper middle income\",\"Lower middle income\",\"High income\",\"Lower middle income\",null,\"High income\",\"Lower middle income\",\"Upper middle income\",\"High income\",\"Low income\",\"High income\",\"High income\",\"High income\",\"High income\",\"Lower middle income\",\"Low income\",\"Upper middle income\",null,\"Low income\",\"High income\",\"Lower middle income\",\"Lower middle income\",\"Low income\",\"Upper middle income\",null,\"High income\",\"High income\",\"Low income\",\"High income\",\"Lower middle income\",\"Upper middle income\",\"Lower middle income\",\"Low income\",null,\"Upper middle income\",\"High income\",\"Lower middle income\",\"Upper middle income\",\"High income\",\"Upper middle income\",\"Upper middle income\",\"Low income\",\"Upper middle income\",\"High income\",\"High income\",\"Lower middle income\",null,\"High income\",\"High income\",\"High income\",\"Lower middle income\",\"Lower middle income\",\"Upper middle income\",\"Lower middle income\",null,null,\"Low income\",\"Lower middle income\",\"Lower middle income\",null],[\"IDA\",\"IBRD\",\"IBRD\",\"NLC\",\"NLC\",\"IBRD\",null,\"IBRD\",\"IBRD\",\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"IBRD\",\"NLC\",\"NLC\",\"IDA\",\"IBRD\",\"IBRD\",\"NLC\",\"Blend\",\"IDA\",\"NLC\",\"IDA\",\"IBRD\",null,\"IBRD\",\"IBRD\",null,\"IBRD\",null,\"NLC\",\"NLC\",\"IBRD\",\"IDA\",\"IDA\",\"Blend\",\"IDA\",\"Blend\",\"NLC\",\"NLC\",\"IDA\",\"IDA\",\"IBRD\",\"IBRD\",\"NLC\",\"NLC\",null,null,\"IBRD\",\"IDA\",\"Blend\",null,\"IBRD\",\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"NLC\",\"IDA\",\"NLC\",\"IDA\",\"NLC\",\"IDA\",\"Blend\",\"IBRD\",\"IBRD\",\"IBRD\",\"IBRD\",\"IBRD\",\"IDA\",\"NLC\",\"Blend\",\"IDA\",null,\"NLC\",\"Blend\",\"NLC\",\"NLC\",null,\"NLC\",null,\"IBRD\",\"IDA\",\"IBRD\",\"NLC\",\"IDA\",\"NLC\",\"NLC\",\"NLC\",\"Blend\",null,\"NLC\",\"IBRD\",null,\"IDA\",\"IDA\",\"IDA\",\"IDA\",null,null,\"IDA\",\"NLC\",\"NLC\",\"IBRD\",\"IBRD\",\"IBRD\",\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"NLC\",\"IBRD\",\"NLC\",null,\"IBRD\",\"IBRD\",\"Blend\",\"IDA\",\"IDA\",\"NLC\",\"IDA\",\"IDA\",\"NLC\",\"IBRD\",\"IDA\",\"IDA\",\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"IDA\",\"IDA\",\"IBRD\",\"IDA\",\"IDA\",\"NLC\",\"IDA\",null,\"IDA\",\"IBRD\",null,\"IBRD\",\"IDA\",\"NLC\",\"IBRD\",\"IBRD\",null,\"IBRD\",\"IDA\",\"IDA\",\"IBRD\",\"IBRD\",\"IDA\",\"NLC\",\"NLC\",\"NLC\",\"IDA\",\"IDA\",\"Blend\",null,null,\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"Blend\",\"IBRD\",\"IBRD\",\"Blend\",\"IBRD\",\"IBRD\",\"IBRD\",null,\"IBRD\",\"NLC\",\"NLC\",\"NLC\",\"NLC\",\"IBRD\",\"IBRD\",\"IBRD\",\"IDA\",null,null,null,\"IBRD\",\"Blend\",\"NLC\",null,\"Blend\",\"IDA\",\"NLC\",\"IDA\",null,\"NLC\",\"IDA\",\"IBRD\",\"IBRD\",\"IDA\",\"NLC\",\"NLC\",\"NLC\",\"NLC\",\"IDA\",\"IDA\",\"IBRD\",null,\"IDA\",\"NLC\",\"IDA\",\"NLC\",\"IDA\",\"IBRD\",null,\"NLC\",\"NLC\",\"IDA\",\"NLC\",\"IDA\",\"IBRD\",\"Blend\",\"IDA\",null,\"IDA\",\"IBRD\",\"IBRD\",\"IBRD\",\"NLC\",\"IDA\",\"IBRD\",\"IDA\",\"IBRD\",\"NLC\",\"NLC\",\"IDA\",null,\"NLC\",\"NLC\",\"IBRD\",\"Blend\",\"IDA\",\"IBRD\",\"IBRD\",null,null,\"IDA\",\"IDA\",\"Blend\",null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>ISO-alpha3 Code<\\/th>\\n      <th>Country or Area<\\/th>\\n      <th>Region Code<\\/th>\\n      <th>Region Name<\\/th>\\n      <th>Sub-region Code<\\/th>\\n      <th>Sub-region Name<\\/th>\\n      <th>Intermediate Region Code<\\/th>\\n      <th>Intermediate Region Name<\\/th>\\n      <th>M49 Code<\\/th>\\n      <th>ISO-alpha2 Code<\\/th>\\n      <th>LDC<\\/th>\\n      <th>LLDC<\\/th>\\n      <th>SIDS<\\/th>\\n      <th>UN<\\/th>\\n      <th>WB Region<\\/th>\\n      <th>Income group<\\/th>\\n      <th>Lending category<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[11,12,13,14]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"ISO-alpha3 Code\",\"targets\":1},{\"name\":\"Country or Area\",\"targets\":2},{\"name\":\"Region Code\",\"targets\":3},{\"name\":\"Region Name\",\"targets\":4},{\"name\":\"Sub-region Code\",\"targets\":5},{\"name\":\"Sub-region Name\",\"targets\":6},{\"name\":\"Intermediate Region Code\",\"targets\":7},{\"name\":\"Intermediate Region Name\",\"targets\":8},{\"name\":\"M49 Code\",\"targets\":9},{\"name\":\"ISO-alpha2 Code\",\"targets\":10},{\"name\":\"LDC\",\"targets\":11},{\"name\":\"LLDC\",\"targets\":12},{\"name\":\"SIDS\",\"targets\":13},{\"name\":\"UN\",\"targets\":14},{\"name\":\"WB Region\",\"targets\":15},{\"name\":\"Income group\",\"targets\":16},{\"name\":\"Lending category\",\"targets\":17}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n::::\n:::::\n\n:::\n\n::::\n:::::\n\n## Analysing `compositions` data\n\n### Multiple Group Membership\n\nLooking again at the `compositions` dataset (Tab: WB `compositions`\" of @exm-wb-inspect) we have to realize that the many grouping criteria are overlapping and therefore multiplicating the relations to specific countries. Every country belongs at least to three different groups. The leader in this respect is the [Union of the Comoros](https://www.britannica.com/place/Comoros), an archipelagic country made up of three islands in Southeastern Africa, located at the northern end of the Mozambique Channel in the Indian Ocean. Comoros is according to the World Bank classification member of 18 different groups. \n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-multiple-group-membership}\n: Multiple group membership according to the different WB criteria\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_compositions <- base::readRDS(\"data/wb/wb_compositions.rds\") \n\nglue::glue(\"********* List countries with the most gropu memberships **********\")\nwb_compositions |> \n    dplyr::group_by(WB_Country_Name) |> \n    dplyr::summarize(n = dplyr::n()) |> \n    dplyr::arrange(dplyr::desc(n)) |> \n    utils::head()\n\n\nglue::glue(\"\")\nglue::glue(\"************** Display group memebership of Comoros **************\")\nwb_compositions |> \n    dplyr::filter(WB_Country_Name == \"Comoros\") |> \n    print(n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ********* List countries with the most gropu memberships **********\n#> # A tibble: 6 × 2\n#>   WB_Country_Name           n\n#>   <chr>                 <int>\n#> 1 Comoros                  18\n#> 2 São Tomé and Príncipe    16\n#> 3 Djibouti                 15\n#> 4 Kiribati                 15\n#> 5 Mauritania               15\n#> 6 Solomon Islands          15\n#> \n#> ************** Display group memebership of Comoros **************\n#> # A tibble: 18 × 4\n#>    WB_Group_Code WB_Group_Name                   WB_Country_Code WB_Country_Name\n#>    <chr>         <chr>                           <chr>           <chr>          \n#>  1 AFE           Africa Eastern and Southern     COM             Comoros        \n#>  2 ARB           Arab World                      COM             Comoros        \n#>  3 FCS           Fragile and conflict affected … COM             Comoros        \n#>  4 HPC           Heavily indebted poor countrie… COM             Comoros        \n#>  5 IBT           IDA & IBRD total                COM             Comoros        \n#>  6 IDX           IDA only                        COM             Comoros        \n#>  7 IDA           IDA total                       COM             Comoros        \n#>  8 LDC           Least developed countries: UN … COM             Comoros        \n#>  9 LMY           Low & middle income             COM             Comoros        \n#> 10 LMC           Lower middle income             COM             Comoros        \n#> 11 MIC           Middle income                   COM             Comoros        \n#> 12 OSS           Other small states              COM             Comoros        \n#> 13 PRE           Pre-demographic dividend        COM             Comoros        \n#> 14 SST           Small states (SST)              COM             Comoros        \n#> 15 SSF           Sub-Saharan Africa              COM             Comoros        \n#> 16 SSA           Sub-Saharan Africa (excluding … COM             Comoros        \n#> 17 TSS           Sub-Saharan Africa (IDA & IBRD) COM             Comoros        \n#> 18 WLD           World                           COM             Comoros\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::::\n:::::\n\n### More African Groupings\n\nA second observation is that the countries classified in \"Sub-Saharan Africa\" are also members of \"African Western and Central\" or \"Africa Eastern & Southern\". We have therefore a second regional group in addition to the already displayed \"WB Standard\" group (Tab: \"WB Standard\" in @exm-wb-separate-countries). In addition to the seven groups of \"WB Standard\" we have another classification with eight different regional areas.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-another-regional-grouping}\n: Another regional grouping of the WB classification: `WB Standard2`\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_compositions <- base::readRDS(\"data/wb/wb_compositions.rds\") \n\nwb_grouping2 <- wb_compositions |> \n  dplyr::filter(\n      WB_Group_Code == \"AFE\" |\n      WB_Group_Code == \"AFW\" |\n      WB_Group_Code == \"EAS\" |\n      WB_Group_Code == \"ECS\" |\n      WB_Group_Code == \"LCN\" |\n      WB_Group_Code == \"MEA\" |\n      WB_Group_Code == \"NAC\" |\n      WB_Group_Code == \"SAS\" \n  )\n\npb_save_data_file(\"wb\", wb_grouping2, \"wb_grouping2.rds\")\n\n(\n    wb_standard2 <- pb_class_scheme(\n            df = wb_grouping2,\n            sel1 = rlang::quo(WB_Country_Name),\n            sel2 = rlang::quo(WB_Group_Name)\n            )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-d44847426e1db2a9842f\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d44847426e1db2a9842f\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],[\"Africa Eastern and Southern\",\"Africa Western and Central\",\"East Asia &amp; Pacific\",\"Europe &amp; Central Asia\",\"Latin America &amp; Caribbean\",\"Middle East &amp; North Africa\",\"North America\",\"South Asia\"],[\"Angola; Botswana; Burundi; Comoros; Congo, Dem. Rep.; Eritrea; Eswatini; Ethiopia; Kenya; Lesotho; Madagascar; Malawi; Mauritius; Mozambique; Namibia; Rwanda; São Tomé and Príncipe; Seychelles; Somalia; South Africa; South Sudan; Sudan; Tanzania; Uganda; Zambia; Zimbabwe ;\",\"Benin; Burkina Faso; Cabo Verde; Cameroon; Central African Republic; Chad; Congo, Rep.; Côte d’Ivoire; Equatorial Guinea; Gabon; Gambia, The; Ghana; Guinea; Guinea-Bissau; Liberia; Mali; Mauritania; Niger; Nigeria; Senegal; Sierra Leone; Togo ;\",\"American Samoa; Australia; Brunei Darussalam; Cambodia; China; Fiji; French Polynesia; Guam; Hong Kong SAR, China; Indonesia; Japan; Kiribati; Korea, Dem. People's Rep.; Korea, Rep.; Lao PDR; Macao SAR, China; Malaysia; Marshall Islands; Micronesia, Fed. Sts.; Mongolia; Myanmar; Nauru; New Caledonia; New Zealand; Northern Mariana Islands; Palau; Papua New Guinea; Philippines; Samoa; Singapore; Solomon Islands; Taiwan, China; Thailand; Timor-Leste; Tonga; Tuvalu; Vanuatu; Vietnam ;\",\"Albania; Andorra; Armenia; Austria; Azerbaijan; Belarus; Belgium; Bosnia and Herzegovina; Bulgaria; Channel Islands; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Georgia; Germany; Gibraltar; Greece; Greenland; Hungary; Iceland; Ireland; Isle of Man; Italy; Kazakhstan; Kosovo; Kyrgyz Republic; Latvia; Liechtenstein; Lithuania; Luxembourg; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway; Poland; Portugal; Romania; Russian Federation; San Marino; Serbia; Slovak Republic; Slovenia; Spain; Sweden; Switzerland; Tajikistan; Türkiye; Turkmenistan; Ukraine; United Kingdom; Uzbekistan ;\",\"Antigua and Barbuda; Argentina; Aruba; Bahamas, The; Barbados; Belize; Bolivia; Brazil; British Virgin Islands; Cayman Islands; Chile; Colombia; Costa Rica; Cuba; Curaçao; Dominica; Dominican Republic; Ecuador; El Salvador; Grenada; Guatemala; Guyana; Haiti; Honduras; Jamaica; Mexico; Nicaragua; Panama; Paraguay; Peru; Puerto Rico; Sint Maarten (Dutch part); St. Kitts and Nevis; St. Lucia; St. Martin (French part); St. Vincent and the Grenadines; Suriname; Trinidad and Tobago; Turks and Caicos Islands; Uruguay; Venezuela, RB; Virgin Islands (U.S.) ;\",\"Algeria; Bahrain; Djibouti; Egypt, Arab Rep.; Iran, Islamic Rep.; Iraq; Israel; Jordan; Kuwait; Lebanon; Libya; Malta; Morocco; Oman; Qatar; Saudi Arabia; Syrian Arab Republic; Tunisia; United Arab Emirates; West Bank and Gaza; Yemen, Rep. ;\",\"Bermuda; Canada; United States ;\",\"Afghanistan; Bangladesh; Bhutan; India; Maldives; Nepal; Pakistan; Sri Lanka ;\"],[26,22,38,58,42,21,3,8]],\"container\":\"<table class=\\\"cell-border compact stripe\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>WB_Group_Name<\\/th>\\n      <th>Country<\\/th>\\n      <th>N<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":25,\"lengthMenu\":[5,10,15,20,25,50],\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":3},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"WB_Group_Name\",\"targets\":1},{\"name\":\"Country\",\"targets\":2},{\"name\":\"N\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n***\n\n`WB_Group_Name` is similar to the classification scheme \"WB Standard\", but instead of only **7 regions** it has now with **8 regions** one region more but with **218** the same number of countries.\n\nThe difference is caused by the division of the meta-region \"Sub-Saharan Africa\" into \"Africa Eastern and Southern\" and \"Africa Western and Central\". All the other groupings are the same as in the Tab \"WB Standard\" of @exm-wb-separate-countries. \n::::\n:::::\n\n### Integrating 2nd regional grouping\n\nI will add this second regional grouping of the World Bank classification with the name of `WB Region2` into my combined meta dataset \"data/meta/m49_ext.rds\" where I collect all different groupings criteria.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-wb-integrate-region2}\n: Integrating the second regional World Bank grouping into the extended M49 dataset\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm49_ext <- base::readRDS(\"data/meta/m49_ext.rds\")\nwb_grouping2 <- base::readRDS(\"data/wb/wb_grouping2.rds\") |> \n  dplyr::filter(WB_Country_Name != \"Channel Islands\")\n  \n\nm49_ext2 <- dplyr::full_join(\n  m49_ext, wb_grouping2, \n  by = dplyr::join_by(`ISO-alpha3 Code` == WB_Country_Code)\n  ) |> \n  dplyr::select(-WB_Country_Name) |> \n  dplyr::rename(`WB Region2` = WB_Group_Name) |> \n  dplyr::relocate(WB_Group_Code, .before = `WB Region`) |> \n  dplyr::relocate(`WB Region2`, .after = `WB Region`)\n\npb_save_data_file(\"meta\", m49_ext2, \"m49_ext2.rds\")\n\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(m49_ext2)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(m49_ext2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |m49_ext2 |\n|Number of rows           |250      |\n|Number of columns        |19       |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |15       |\n|numeric                  |4        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable            | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|ISO-alpha3 Code          |         0|          1.00|   3|   3|     0|      250|          0|\n|Country or Area          |         0|          1.00|   4|  52|     0|      250|          0|\n|Region Code              |         2|          0.99|   3|   3|     0|        5|          0|\n|Region Name              |         2|          0.99|   4|   8|     0|        5|          0|\n|Sub-region Code          |         2|          0.99|   3|   3|     0|       17|          0|\n|Sub-region Name          |         2|          0.99|   9|  31|     0|       17|          0|\n|Intermediate Region Code |         2|          0.99|   3|   3|     0|       22|          0|\n|Intermediate Region Name |         2|          0.99|   9|  25|     0|       22|          0|\n|M49 Code                 |         2|          0.99|   3|   3|     0|      248|          0|\n|ISO-alpha2 Code          |         0|          1.00|   2|   2|     0|      249|          0|\n|WB_Group_Code            |        33|          0.87|   3|   3|     0|        8|          0|\n|WB Region                |        33|          0.87|  10|  26|     0|        7|          0|\n|WB Region2               |        33|          0.87|  10|  27|     0|        8|          0|\n|Income group             |        33|          0.87|  10|  19|     0|        4|          0|\n|Lending category         |        33|          0.87|   3|   5|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate| mean|   sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|----:|----:|--:|---:|---:|---:|----:|:-----|\n|LDC           |         2|          0.99| 0.19| 0.39|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|LLDC          |         2|          0.99| 0.13| 0.34|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|SIDS          |         2|          0.99| 0.21| 0.41|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|UN            |         2|          0.99| 0.79| 0.41|  0|   1|   1|   1|    1|▂▁▁▁▇ |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 250\n#> Columns: 19\n#> $ `ISO-alpha3 Code`          <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\", \"AND\", \"AGO\", \"…\n#> $ `Country or Area`          <chr> \"Afghanistan\", \"Albania\", \"Algeria\", \"Ameri…\n#> $ `Region Code`              <chr> \"142\", \"150\", \"002\", \"009\", \"150\", \"002\", \"…\n#> $ `Region Name`              <chr> \"Asia\", \"Europe\", \"Africa\", \"Oceania\", \"Eur…\n#> $ `Sub-region Code`          <chr> \"034\", \"039\", \"015\", \"061\", \"039\", \"202\", \"…\n#> $ `Sub-region Name`          <chr> \"Southern Asia\", \"Southern Europe\", \"Northe…\n#> $ `Intermediate Region Code` <chr> \"034\", \"039\", \"015\", \"061\", \"039\", \"017\", \"…\n#> $ `Intermediate Region Name` <chr> \"Southern Asia\", \"Southern Europe\", \"Northe…\n#> $ `M49 Code`                 <chr> \"004\", \"008\", \"012\", \"016\", \"020\", \"024\", \"…\n#> $ `ISO-alpha2 Code`          <chr> \"AF\", \"AL\", \"DZ\", \"AS\", \"AD\", \"AO\", \"AI\", \"…\n#> $ LDC                        <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n#> $ LLDC                       <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0…\n#> $ SIDS                       <dbl> 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1…\n#> $ UN                         <dbl> 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1…\n#> $ WB_Group_Code              <chr> \"SAS\", \"ECS\", \"MEA\", \"EAS\", \"ECS\", \"AFE\", N…\n#> $ `WB Region`                <chr> \"South Asia\", \"Europe & Central Asia\", \"Mid…\n#> $ `WB Region2`               <chr> \"South Asia\", \"Europe & Central Asia\", \"Mid…\n#> $ `Income group`             <chr> \"Low income\", \"Upper middle income\", \"Upper…\n#> $ `Lending category`         <chr> \"IDA\", \"IBRD\", \"IBRD\", \"NLC\", \"NLC\", \"IBRD\"…\n```\n\n\n:::\n:::\n\n\n\n\n\n***\n\nChecking the missing values: UN M49 - WB = 250 (incl. Sark) - 218 - 1 (Channel Islands) + 2 (Kosovo and Taiwan already from World Bank dataset integrated into UN M49 extended.) = 33 missing values.\n::::\n:::::\n\n\n### Integrating simple groups\n\nMy supplements to the UN M49 changes the original file. To differentiate it from the UN M49 source I will call it **M49 extended**.\n\nWith the next step I will add simple groups from the World Bank classification to the M49 extended dataset. Under \"simple\" I understand groups with only two values: Yes and No or in my case 1 and 0.\n\n\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-create-simple-groups}\n: Integrating simple groups into the M49 extended dataset\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Function for creating simple groups #########################\npb_add_simple_group <- function(df_comp, df_ext, group_name){\n  df_comp <- df_comp |> \n    dplyr::filter(WB_Group_Name == !!group_name) |>\n    dplyr::select(2,3) |> \n    dplyr::rename(!!group_name := WB_Group_Name) |> \n    dplyr::mutate(!!group_name := 1)\n  \n  dplyr::full_join(\n      df_ext, df_comp,\n      by = dplyr::join_by(`ISO-alpha3 Code` == WB_Country_Code)\n    )\n}\n\n##  Calling function to create simple groups   ################\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  base::readRDS(\"data/meta/m49_ext2.rds\"),\n  \"Arab World\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Euro area\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"OECD members\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"European Union\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Small states (SST)\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Central Europe and the Baltics\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Fragile and conflict affected situations\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Heavily indebted poor countries (HIPC)\"\n  )\n\n## identical with M49 `LCD` column ###################\n## Least developed countries: UN classification \n\n# m49_ext3 <- pb_add_simple_group(\n#   base::readRDS(\"data/wb/wb_compositions.rds\"),\n#   m49_ext3,\n#   \"Least developed countries: UN classification\"\n#   )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"IBRD only\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"IDA & IBRD total\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"IDA blend\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"IDA only\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"IDA total\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Middle income\"\n  )\n\nm49_ext3 <- pb_add_simple_group(\n  base::readRDS(\"data/wb/wb_compositions.rds\"),\n  m49_ext3,\n  \"Low & middle income\"\n  )\n\nm49_ext3 <- m49_ext3 |>\n  dplyr::mutate(dplyr::across(\n    `Arab World`:`Low & middle income`, ~ tidyr::replace_na(., 0)))\n\n  \npb_save_data_file(\"meta\", m49_ext3, \"m49_ext3.rds\")\n\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(m49_ext3)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(m49_ext3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |m49_ext3 |\n|Number of rows           |250      |\n|Number of columns        |34       |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |15       |\n|numeric                  |19       |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable            | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|ISO-alpha3 Code          |         0|          1.00|   3|   3|     0|      250|          0|\n|Country or Area          |         0|          1.00|   4|  52|     0|      250|          0|\n|Region Code              |         2|          0.99|   3|   3|     0|        5|          0|\n|Region Name              |         2|          0.99|   4|   8|     0|        5|          0|\n|Sub-region Code          |         2|          0.99|   3|   3|     0|       17|          0|\n|Sub-region Name          |         2|          0.99|   9|  31|     0|       17|          0|\n|Intermediate Region Code |         2|          0.99|   3|   3|     0|       22|          0|\n|Intermediate Region Name |         2|          0.99|   9|  25|     0|       22|          0|\n|M49 Code                 |         2|          0.99|   3|   3|     0|      248|          0|\n|ISO-alpha2 Code          |         0|          1.00|   2|   2|     0|      249|          0|\n|WB_Group_Code            |        33|          0.87|   3|   3|     0|        8|          0|\n|WB Region                |        33|          0.87|  10|  26|     0|        7|          0|\n|WB Region2               |        33|          0.87|  10|  27|     0|        8|          0|\n|Income group             |        33|          0.87|  10|  19|     0|        4|          0|\n|Lending category         |        33|          0.87|   3|   5|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable                            | n_missing| complete_rate| mean|   sd| p0| p25| p50| p75| p100|hist  |\n|:----------------------------------------|---------:|-------------:|----:|----:|--:|---:|---:|---:|----:|:-----|\n|LDC                                      |         2|          0.99| 0.19| 0.39|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|LLDC                                     |         2|          0.99| 0.13| 0.34|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|SIDS                                     |         2|          0.99| 0.21| 0.41|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|UN                                       |         2|          0.99| 0.79| 0.41|  0|   1|   1|   1|    1|▂▁▁▁▇ |\n|Arab World                               |         0|          1.00| 0.09| 0.28|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Euro area                                |         0|          1.00| 0.08| 0.27|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|OECD members                             |         0|          1.00| 0.15| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|European Union                           |         0|          1.00| 0.11| 0.31|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Small states (SST)                       |         0|          1.00| 0.16| 0.37|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|Central Europe and the Baltics           |         0|          1.00| 0.04| 0.21|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Fragile and conflict affected situations |         0|          1.00| 0.16| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|Heavily indebted poor countries (HIPC)   |         0|          1.00| 0.16| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|IBRD only                                |         0|          1.00| 0.27| 0.45|  0|   0|   0|   1|    1|▇▁▁▁▃ |\n|IDA & IBRD total                         |         0|          1.00| 0.58| 0.49|  0|   0|   1|   1|    1|▆▁▁▁▇ |\n|IDA blend                                |         0|          1.00| 0.07| 0.25|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|IDA only                                 |         0|          1.00| 0.24| 0.43|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|IDA total                                |         0|          1.00| 0.31| 0.46|  0|   0|   0|   1|    1|▇▁▁▁▃ |\n|Middle income                            |         0|          1.00| 0.42| 0.49|  0|   0|   0|   1|    1|▇▁▁▁▆ |\n|Low & middle income                      |         0|          1.00| 0.52| 0.50|  0|   0|   1|   1|    1|▇▁▁▁▇ |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 250\n#> Columns: 34\n#> $ `ISO-alpha3 Code`                          <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\",…\n#> $ `Country or Area`                          <chr> \"Afghanistan\", \"Albania\", \"…\n#> $ `Region Code`                              <chr> \"142\", \"150\", \"002\", \"009\",…\n#> $ `Region Name`                              <chr> \"Asia\", \"Europe\", \"Africa\",…\n#> $ `Sub-region Code`                          <chr> \"034\", \"039\", \"015\", \"061\",…\n#> $ `Sub-region Name`                          <chr> \"Southern Asia\", \"Southern …\n#> $ `Intermediate Region Code`                 <chr> \"034\", \"039\", \"015\", \"061\",…\n#> $ `Intermediate Region Name`                 <chr> \"Southern Asia\", \"Southern …\n#> $ `M49 Code`                                 <chr> \"004\", \"008\", \"012\", \"016\",…\n#> $ `ISO-alpha2 Code`                          <chr> \"AF\", \"AL\", \"DZ\", \"AS\", \"AD…\n#> $ LDC                                        <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, …\n#> $ LLDC                                       <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ SIDS                                       <dbl> 0, 0, 0, 1, 0, 0, 1, 1, 0, …\n#> $ UN                                         <dbl> 1, 1, 1, 0, 1, 1, 0, 1, 1, …\n#> $ WB_Group_Code                              <chr> \"SAS\", \"ECS\", \"MEA\", \"EAS\",…\n#> $ `WB Region`                                <chr> \"South Asia\", \"Europe & Cen…\n#> $ `WB Region2`                               <chr> \"South Asia\", \"Europe & Cen…\n#> $ `Income group`                             <chr> \"Low income\", \"Upper middle…\n#> $ `Lending category`                         <chr> \"IDA\", \"IBRD\", \"IBRD\", \"NLC…\n#> $ `Arab World`                               <dbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, …\n#> $ `Euro area`                                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `OECD members`                             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `European Union`                           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Small states (SST)`                       <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n#> $ `Central Europe and the Baltics`           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Fragile and conflict affected situations` <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Heavily indebted poor countries (HIPC)`   <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IBRD only`                                <dbl> 0, 1, 1, 0, 0, 1, 0, 1, 1, …\n#> $ `IDA & IBRD total`                         <dbl> 1, 1, 1, 0, 0, 1, 0, 1, 1, …\n#> $ `IDA blend`                                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IDA only`                                 <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IDA total`                                <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Middle income`                            <dbl> 0, 1, 1, 0, 0, 1, 0, 0, 1, …\n#> $ `Low & middle income`                      <dbl> 1, 1, 1, 0, 0, 1, 0, 0, 1, …\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::::\n:::::\n\n### Integrating composite groups\n\nUnder \"composite\" groups I understand columns that have more than two values. In contrast to the simple groups where the column types are numerical, the composite groups are character columns. \"0\" means that the criteria for this column is not applicable.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-create-composite-groups}\n: Integrating composite groups into the M49 extended dataset\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Preparing composition data #################\n## for unique string selection\nwb_compositions2 <- base::readRDS(\"data/wb/wb_compositions.rds\") |> \n    dplyr::filter(\n      WB_Group_Name != \"IDA & IBRD\",\n      WB_Group_Name != \"IDA & IBRD total\") |> \n    dplyr::filter(\n      WB_Group_Name != \"High income\",\n      WB_Group_Name != \"Low income\",\n      WB_Group_Name != \"Upper middle income\",\n      WB_Group_Name != \"Lower middle income\"\n      )\n\npb_save_data_file(\"wb\", wb_compositions2, \"wb_compositions2.rds\")\n\n\n## functions for composite groups\npb_new_composite_group <- function(df_ext, group_name, search_string){\n  df_comp2 <- base::readRDS(\"data/wb/wb_compositions2.rds\")\n  df_comp2 <- df_comp2 |> \n    dplyr::filter(stringr::str_detect(WB_Group_Name, !!search_string)) |>\n    dplyr::rename(!!group_name := WB_Group_Name) |> \n    dplyr::select(2,3) \n  \n  dplyr::full_join(\n    df_ext, df_comp2,\n    by = dplyr::join_by(`ISO-alpha3 Code` == WB_Country_Code)\n    )\n}\n\n\n## create composite groups ##################\n\nm49_ext3 <- base::readRDS(\"data/meta/m49_ext3.rds\")\n\nm49_ext4 <- pb_new_composite_group(\n  m49_ext3,\n  \"Small States\", \n  \"small states\"\n  )\n\nm49_ext4 <- pb_new_composite_group(\n  m49_ext4,\n  \"Excluding High Income\", \n  \"(excluding high income)\"\n  )\n\nm49_ext4 <- pb_new_composite_group(\n  m49_ext4,\n  \"Demographic Divididend\", \n  \"demographic dividend\"\n  )\n\nm49_ext4 <- pb_new_composite_group(\n  m49_ext4,\n  \"IDA & IBRD\", \n  \"(IDA & IBRD)\"\n  )\n\nm49_ext4 <- m49_ext4 |>\n  dplyr::mutate(dplyr::across(\n    `Small States`:`IDA & IBRD`, ~ tidyr::replace_na(., \"0\")))\n\n\npb_save_data_file(\"meta\", m49_ext4, \"m49_ext4.rds\")\n\n\nglue::glue(\"******************* Using skimr::skim() ***************************\")\nskimr::skim(m49_ext4)\nglue::glue(\"\")\nglue::glue(\"****************** Using dplyr::glimpse() *************************\")\ndplyr::glimpse(m49_ext4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ******************* Using skimr::skim() ***************************\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |m49_ext4 |\n|Number of rows           |250      |\n|Number of columns        |38       |\n|_______________________  |         |\n|Column type frequency:   |         |\n|character                |19       |\n|numeric                  |19       |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: character**\n\n|skim_variable            | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|ISO-alpha3 Code          |         0|          1.00|   3|   3|     0|      250|          0|\n|Country or Area          |         0|          1.00|   4|  52|     0|      250|          0|\n|Region Code              |         2|          0.99|   3|   3|     0|        5|          0|\n|Region Name              |         2|          0.99|   4|   8|     0|        5|          0|\n|Sub-region Code          |         2|          0.99|   3|   3|     0|       17|          0|\n|Sub-region Name          |         2|          0.99|   9|  31|     0|       17|          0|\n|Intermediate Region Code |         2|          0.99|   3|   3|     0|       22|          0|\n|Intermediate Region Name |         2|          0.99|   9|  25|     0|       22|          0|\n|M49 Code                 |         2|          0.99|   3|   3|     0|      248|          0|\n|ISO-alpha2 Code          |         0|          1.00|   2|   2|     0|      249|          0|\n|WB_Group_Code            |        33|          0.87|   3|   3|     0|        8|          0|\n|WB Region                |        33|          0.87|  10|  26|     0|        7|          0|\n|WB Region2               |        33|          0.87|  10|  27|     0|        8|          0|\n|Income group             |        33|          0.87|  10|  19|     0|        4|          0|\n|Lending category         |        33|          0.87|   3|   5|     0|        4|          0|\n|Small States             |         0|          1.00|   1|  27|     0|        4|          0|\n|Excluding High Income    |         0|          1.00|   1|  50|     0|        6|          0|\n|Demographic Divididend   |         0|          1.00|   1|  26|     0|        5|          0|\n|IDA & IBRD               |         0|          1.00|   1|  39|     0|        7|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable                            | n_missing| complete_rate| mean|   sd| p0| p25| p50| p75| p100|hist  |\n|:----------------------------------------|---------:|-------------:|----:|----:|--:|---:|---:|---:|----:|:-----|\n|LDC                                      |         2|          0.99| 0.19| 0.39|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|LLDC                                     |         2|          0.99| 0.13| 0.34|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|SIDS                                     |         2|          0.99| 0.21| 0.41|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|UN                                       |         2|          0.99| 0.79| 0.41|  0|   1|   1|   1|    1|▂▁▁▁▇ |\n|Arab World                               |         0|          1.00| 0.09| 0.28|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Euro area                                |         0|          1.00| 0.08| 0.27|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|OECD members                             |         0|          1.00| 0.15| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|European Union                           |         0|          1.00| 0.11| 0.31|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Small states (SST)                       |         0|          1.00| 0.16| 0.37|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|Central Europe and the Baltics           |         0|          1.00| 0.04| 0.21|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|Fragile and conflict affected situations |         0|          1.00| 0.16| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|Heavily indebted poor countries (HIPC)   |         0|          1.00| 0.16| 0.36|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|IBRD only                                |         0|          1.00| 0.27| 0.45|  0|   0|   0|   1|    1|▇▁▁▁▃ |\n|IDA & IBRD total                         |         0|          1.00| 0.58| 0.49|  0|   0|   1|   1|    1|▆▁▁▁▇ |\n|IDA blend                                |         0|          1.00| 0.07| 0.25|  0|   0|   0|   0|    1|▇▁▁▁▁ |\n|IDA only                                 |         0|          1.00| 0.24| 0.43|  0|   0|   0|   0|    1|▇▁▁▁▂ |\n|IDA total                                |         0|          1.00| 0.31| 0.46|  0|   0|   0|   1|    1|▇▁▁▁▃ |\n|Middle income                            |         0|          1.00| 0.42| 0.49|  0|   0|   0|   1|    1|▇▁▁▁▆ |\n|Low & middle income                      |         0|          1.00| 0.52| 0.50|  0|   0|   1|   1|    1|▇▁▁▁▇ |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> ****************** Using dplyr::glimpse() *************************\n#> Rows: 250\n#> Columns: 38\n#> $ `ISO-alpha3 Code`                          <chr> \"AFG\", \"ALB\", \"DZA\", \"ASM\",…\n#> $ `Country or Area`                          <chr> \"Afghanistan\", \"Albania\", \"…\n#> $ `Region Code`                              <chr> \"142\", \"150\", \"002\", \"009\",…\n#> $ `Region Name`                              <chr> \"Asia\", \"Europe\", \"Africa\",…\n#> $ `Sub-region Code`                          <chr> \"034\", \"039\", \"015\", \"061\",…\n#> $ `Sub-region Name`                          <chr> \"Southern Asia\", \"Southern …\n#> $ `Intermediate Region Code`                 <chr> \"034\", \"039\", \"015\", \"061\",…\n#> $ `Intermediate Region Name`                 <chr> \"Southern Asia\", \"Southern …\n#> $ `M49 Code`                                 <chr> \"004\", \"008\", \"012\", \"016\",…\n#> $ `ISO-alpha2 Code`                          <chr> \"AF\", \"AL\", \"DZ\", \"AS\", \"AD…\n#> $ LDC                                        <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, …\n#> $ LLDC                                       <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ SIDS                                       <dbl> 0, 0, 0, 1, 0, 0, 1, 1, 0, …\n#> $ UN                                         <dbl> 1, 1, 1, 0, 1, 1, 0, 1, 1, …\n#> $ WB_Group_Code                              <chr> \"SAS\", \"ECS\", \"MEA\", \"EAS\",…\n#> $ `WB Region`                                <chr> \"South Asia\", \"Europe & Cen…\n#> $ `WB Region2`                               <chr> \"South Asia\", \"Europe & Cen…\n#> $ `Income group`                             <chr> \"Low income\", \"Upper middle…\n#> $ `Lending category`                         <chr> \"IDA\", \"IBRD\", \"IBRD\", \"NLC…\n#> $ `Arab World`                               <dbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, …\n#> $ `Euro area`                                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `OECD members`                             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `European Union`                           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Small states (SST)`                       <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n#> $ `Central Europe and the Baltics`           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Fragile and conflict affected situations` <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Heavily indebted poor countries (HIPC)`   <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IBRD only`                                <dbl> 0, 1, 1, 0, 0, 1, 0, 1, 1, …\n#> $ `IDA & IBRD total`                         <dbl> 1, 1, 1, 0, 0, 1, 0, 1, 1, …\n#> $ `IDA blend`                                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IDA only`                                 <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `IDA total`                                <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n#> $ `Middle income`                            <dbl> 0, 1, 1, 0, 0, 1, 0, 0, 1, …\n#> $ `Low & middle income`                      <dbl> 1, 1, 1, 0, 0, 1, 0, 0, 1, …\n#> $ `Small States`                             <chr> \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n#> $ `Excluding High Income`                    <chr> \"0\", \"Europe & Central Asia…\n#> $ `Demographic Divididend`                   <chr> \"Pre-demographic dividend\",…\n#> $ `IDA & IBRD`                               <chr> \"South Asia (IDA & IBRD)\", …\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n::::\n:::::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}